# GENERATED by scripts/build_era_lite.py from notebooks/era_candidate_causal.ipynb -- DO NOT EDIT.
# Edit the FULL notebook, then re-run the build script (see its docstring for the sync workflow).
# Deferred top-level script from cells 2-4, in original cell
# order; exec'd into scaffold.py's module globals by
# load_baselines() with cwd = the reproducibility repo.

# ----- cell 2 script -----
with open ('data/catalogues/anss_catalog1932.obj', 'rb') as obj:
        cat4_1932 = pickle.load(obj)


# ----- cell 3 script -----


# ----- cell 4 (baselines), verbatim -----
# @title benchmark forecasts by baseline models.

# Downloading and loading the precomputed baseline model (ETAS) score with respect to the observations

with open ('data/catalogues/catalogue_2007_2018.obj', 'rb') as obj:
  catalogue = pickle.load(obj)

def load_etas_scores(filepath: str = "etas_baseline_scores.pkl") -> pd.Series:
    """Loads ETAS scores from a pickle file."""
    return pd.read_pickle(filepath)

url = 'https://raw.githubusercontent.com/smousavi05/ll_etas/main/etas_baseline_scores.pkl'
etas_filename = '/content/pycsep/pre-computed-ll-etas-scores.pkl'

if os.path.exists(etas_filename):
    os.remove(etas_filename)
    print(f"Deleted old file: {etas_filename}")

if not os.path.exists(etas_filename):
    print(f"Downloading ETAS baseline scores to: {etas_filename} ...")
    try:
        urllib.request.urlretrieve(url, etas_filename)
        print("Download complete.")

    except Exception as e:
        print(f"Download failed: {e}")
        # Clean up partial/bad file
        if os.path.exists(etas_filename):
            os.remove(etas_filename)

etas_scores_wrt_obs = load_etas_scores(etas_filename)
print(len(etas_scores_wrt_obs))

# Selected models from CSEP Benchmark dataset
ETAS = pd.read_csv('preprocessed_inputs/ETAS/ETAS_dates.csv', sep=',', header=0)
ETAS_DROneDayMd2 = pd.read_csv('preprocessed_inputs/ETAS_DROneDayMd2/ETAS_DROneDayMd2_dates.csv', sep=',', header=0)
ETAS_HWMd3 = pd.read_csv('preprocessed_inputs/ETAS_HWMd3/ETAS_HWMd3_dates.csv', sep=',', header=0)
ETAS_DROneDayMd295 = pd.read_csv('preprocessed_inputs/ETAS_DROneDayMd295/ETAS_DROneDayMd295_dates.csv', sep=',', header=0)

STEP = pd.read_csv('preprocessed_inputs/STEP/STEP_dates.csv', sep=',', header=0)
STEPJAVA = pd.read_csv('preprocessed_inputs/STEPJAVA/STEPJAVA_dates.csv', sep=',', header=0)

ETAS_DROneDayPPEMd2 = pd.read_csv('preprocessed_inputs/ETAS_DROneDayPPEMd2/ETAS_DROneDayPPEMd2_dates.csv', sep=',', header=0)
K3Md2 = pd.read_csv('preprocessed_inputs/K3Md2/K3Md2_dates.csv', sep=',', header=0)
ETAS_HW_K3_AVERAGE_Md2 = pd.read_csv('preprocessed_inputs/ETAS_HW_K3_AVERAGE_Md2/ETAS_HW_K3_AVERAGE_Md2_dates.csv', sep=',', header=0)
ETASSYN_DROneDayMd295 = pd.read_csv('preprocessed_inputs/ETASSYN_DROneDayMd295/ETASSYN_DROneDayMd295_dates.csv', sep=',', header=0)

models = [
    ETAS, ETAS_DROneDayMd2, ETAS_HWMd3, ETAS_DROneDayMd295,
    STEP, STEPJAVA,
    ETAS_DROneDayPPEMd2,
    K3Md2,
    ETAS_HW_K3_AVERAGE_Md2,
    ETASSYN_DROneDayMd295
]
models_name = [
    'ETAS', 'ETAS-DROneDayMd2', 'ETAS-HWMd3', 'ETAS-DROneDayMd2.95',
    'STEP', 'STEPJAVA',
    'ETAS-DROneDayPPEMd2',
    'K3Md2',
    'ETAS-HW-K3-AVERAGE-Md2',
    'ETASSYN-DROneDayMd2.95'
]

def format_dates(f_dates):
    return pd.to_datetime(f_dates['date'], format='%Y-%m-%d').tolist()

forecast_dates_org = [format_dates(m) for m in models]
forecast_dates = {name: format_dates(m) for name, m in zip(models_name, models)}

################################################
# event counts by forecasting models - these are used for n-tests
def get_filtered_catalog(model_key, cat_path='data/catalogues/catalogue_2007_2018.obj'):
    start_epoch = csep.utils.time_utils.strptime_to_utc_epoch(str(min(forecast_dates[model_key])))
    end_epoch = csep.utils.time_utils.strptime_to_utc_epoch(str(max(forecast_dates[model_key])))
    filters = [f'origin_time >= {start_epoch}', f'origin_time < {end_epoch}']
    with open(cat_path, 'rb') as obj:
        cat = pickle.load(obj)
    return cat.filter(filters)

# Compile the observed catalog associated with each forecast model
catalogue_ETAS = get_filtered_catalog('ETAS')
catalogue_ETAS_DROneDayMd2 = get_filtered_catalog('ETAS-DROneDayMd2')
catalogue_ETAS_HWMd3 = get_filtered_catalog('ETAS-HWMd3')
catalogue_ETAS_DROneDayMd295 = get_filtered_catalog('ETAS-DROneDayMd2.95')

catalogue_STEP = get_filtered_catalog('STEP')
catalogue_STEPJAVA = get_filtered_catalog('STEPJAVA', 'data/catalogues/catalogue_2007_2018_sj.obj')

catalogue_ETAS_DROneDayPPEMd2 = get_filtered_catalog('ETAS-DROneDayPPEMd2')
catalogue_K3Md2 = get_filtered_catalog('K3Md2')
catalogue_ETAS_HW_K3_AVERAGE_Md2 = get_filtered_catalog('ETAS-HW-K3-AVERAGE-Md2')
catalogue_ETASSYN_DROneDayMd295 = get_filtered_catalog('ETASSYN-DROneDayMd2.95')

# read event counts by forecast models
ETAS_ncounts = np.genfromtxt('preprocessed_inputs/ETAS/ETAS_ncounts.dat', delimiter='\t')
ETAS_DROneDayMd2_ncounts = np.genfromtxt('preprocessed_inputs/ETAS_DROneDayMd2/ETAS_DROneDayMd2_ncounts.dat', delimiter='\t')
ETAS_HWMd3_ncounts = np.genfromtxt('preprocessed_inputs/ETAS_HWMd3/ETAS_HWMd3_ncounts.dat', delimiter='\t')
ETAS_DROneDayMd295_ncounts = np.genfromtxt('preprocessed_inputs/ETAS_DROneDayMd295/ETAS_DROneDayMd295_ncounts.dat',  delimiter='\t')

STEP_ncounts = np.genfromtxt('preprocessed_inputs/STEP/STEP_ncounts.dat', delimiter='\t')
STEPJAVA_ncounts = np.genfromtxt('preprocessed_inputs/STEPJAVA/STEPJAVA_ncounts.dat', delimiter='\t')

ETAS_DROneDayPPEMd2_ncounts = np.genfromtxt('preprocessed_inputs/ETAS_DROneDayPPEMd2/ETAS_DROneDayPPEMd2_ncounts.dat', delimiter='\t')
K3Md2_ncounts = np.genfromtxt('preprocessed_inputs/K3Md2/K3Md2_ncounts.dat',  delimiter='\t')
ETAS_HW_K3_AVERAGE_Md2_ncounts = np.genfromtxt('preprocessed_inputs/ETAS_HW_K3_AVERAGE_Md2/ETAS_HW_K3_AVERAGE_Md2_ncounts.dat',  delimiter='\t')
ETASSYN_DROneDayMd295_ncounts = np.genfromtxt('preprocessed_inputs/ETASSYN_DROneDayMd295/ETASSYN_DROneDayMd295_ncounts.dat', delimiter='\t')

##########################################
# number test results
with open ('data/catalogues/catalogue_2007_2018.obj', 'rb') as obj:
  catalogue = pickle.load(obj)

ntest_ETAS = number_test(ETAS_ncounts, catalogue)
ntest_ETAS_DROneDayMd2 = number_test(ETAS_DROneDayMd2_ncounts, catalogue_ETAS_DROneDayMd2)
ntest_ETAS_HWMd3 = number_test(ETAS_HWMd3_ncounts, catalogue_ETAS_HWMd3)
ntest_ETAS_DROneDayMd295 = number_test(ETAS_DROneDayMd295_ncounts, catalogue_ETAS_DROneDayMd295)

ntest_STEP = number_test(STEP_ncounts, catalogue_STEP)
ntest_STEPJAVA = number_test(STEPJAVA_ncounts, catalogue_STEPJAVA)

ntest_ETAS_DROneDayPPEMd2 = number_test(ETAS_DROneDayPPEMd2_ncounts, catalogue_ETAS_DROneDayPPEMd2)
ntest_K3Md2 = number_test(K3Md2_ncounts, catalogue_K3Md2)
ntest_ETAS_HW_K3_AVERAGE_Md2 = number_test(ETAS_HW_K3_AVERAGE_Md2_ncounts, catalogue_ETAS_HW_K3_AVERAGE_Md2)
ntest_ETASSYN_DROneDayMd295 = number_test(ETASSYN_DROneDayMd295_ncounts, catalogue_ETASSYN_DROneDayMd295)

###########################################
# Sequence Data Preparation

# 1. Assign counts to all model DataFrames
model_dicts = {
    'ETAS': (ETAS, ETAS_ncounts, 'n_ETAS'),
    'STEP': (STEP, STEP_ncounts, 'n_STEP'),
    'STEPJAVA': (STEPJAVA, STEPJAVA_ncounts, 'n_STEPJAVA'),
    'ETAS_DROneDayMd2': (ETAS_DROneDayMd2, ETAS_DROneDayMd2_ncounts, 'n_ETAS_DROneDayMd2'),
    'ETAS_HWMd3': (ETAS_HWMd3, ETAS_HWMd3_ncounts, 'n_ETAS_HWMd3'),
    'ETAS_DROneDayMd295': (ETAS_DROneDayMd295, ETAS_DROneDayMd295_ncounts, 'n_ETAS_DROneDayMd295'),
    'ETAS_DROneDayPPEMd2': (ETAS_DROneDayPPEMd2, ETAS_DROneDayPPEMd2_ncounts, 'n_ETAS_DROneDayPPEMd2'),
    'K3Md2': (K3Md2, K3Md2_ncounts, 'n_K3Md2'),
    'ETAS_HW_K3_AVERAGE_Md2': (ETAS_HW_K3_AVERAGE_Md2, ETAS_HW_K3_AVERAGE_Md2_ncounts, 'n_ETAS_HW_K3_AVERAGE_Md2'),
    'ETASSYN_DROneDayMd295': (ETASSYN_DROneDayMd295, ETASSYN_DROneDayMd295_ncounts, 'n_ETASSYN_DROneDayMd295'),
}

for name, (df, counts, col_name) in model_dicts.items():
    if col_name not in df.columns:
        df[col_name] = counts

# 2. Universal sequence preparation function
def prep_sequence(start_date, end_date, models, min_mw=3.95):
    # Filter global catalogue
    with open('data/catalogues/catalogue_2007_2018.obj', 'rb') as obj:
        cat = pickle.load(obj)

    start_epoch = time_utils.strptime_to_utc_epoch(f'{start_date} 00:00:00.0')
    end_dt = pd.to_datetime(end_date) + pd.Timedelta(days=1)
    end_epoch = time_utils.strptime_to_utc_epoch(f'{end_dt.strftime("%Y-%m-%d")} 00:00:00.0')

    cat.filter(f'origin_time >= {start_epoch}')
    cat.filter(f'origin_time < {end_epoch}')
    if min_mw > 3.95:
        cat.filter(f'magnitude >= {min_mw}')

    epoch_times = cat.get_epoch_times()
    percentile = 95

    res_dfs, res_plow, res_phigh = {}, {}, {}

    for m in models:
        df, _, col_name = model_dicts[m]
        df_seq = df[(df['date'] >= start_date) & (df['date'] <= end_date)].copy()

        # Calculate obs counts
        obs_counts = []
        for i in range(len(df_seq)):
            d_start = time_utils.strptime_to_utc_epoch(f"{df_seq.date.values[i]} 00:00:00.0")
            d_end_dt = pd.to_datetime(df_seq.date.values[i]) + pd.Timedelta(days=1)
            d_end = time_utils.strptime_to_utc_epoch(f"{d_end_dt.strftime('%Y-%m-%d')} 00:00:00.0")
            obs_counts.append(np.sum((epoch_times >= d_start) & (epoch_times < d_end)))

        df_seq['obs'] = obs_counts

        # Calculate quantiles
        n_vals = df_seq[col_name].astype(float).values
        res_dfs[m] = df_seq
        res_plow[m] = stats.poisson.ppf((1 - percentile/100.)/2., n_vals)
        res_phigh[m] = stats.poisson.ppf(1 - (1 - percentile/100.)/2., n_vals)

    return res_dfs, res_plow, res_phigh

# 3. Apply to all sequences plotted in Figure 4
# Ferndale
f_dfs, f_plow, f_phigh = prep_sequence('2010-01-06', '2010-01-25', ['ETAS', 'STEP'])
ETAS_ferndale, STEP_ferndale = f_dfs['ETAS'], f_dfs['STEP']
ETAS_ferndale_plow95, ETAS_ferndale_phigh95 = f_plow['ETAS'], f_phigh['ETAS']
STEP_ferndale_plow95, STEP_ferndale_phigh95 = f_plow['STEP'], f_phigh['STEP']

# Active
a_dfs, a_plow, a_phigh = prep_sequence('2010-03-31', '2010-04-19', ['ETAS', 'STEP'])
ETAS_active, STEP_active = a_dfs['ETAS'], a_dfs['STEP']
ETAS_active_plow95, ETAS_active_phigh95 = a_plow['ETAS'], a_phigh['ETAS']
STEP_active_plow95, STEP_active_phigh95 = a_plow['STEP'], a_phigh['STEP']

# Swarm
s_dfs, s_plow, s_phigh = prep_sequence('2012-08-22', '2012-09-10', ['ETAS', 'STEP'])
ETAS_swarm, STEP_swarm = s_dfs['ETAS'], s_dfs['STEP']
ETAS_swarm_plow95, ETAS_swarm_phigh95 = s_plow['ETAS'], s_phigh['ETAS']
STEP_swarm_plow95, STEP_swarm_phigh95 = s_plow['STEP'], s_phigh['STEP']

# Mendo
m_dfs, m_plow, m_phigh = prep_sequence('2014-03-06', '2014-03-25', ['ETAS', 'ETAS_DROneDayMd2', 'ETAS_HWMd3',
                                                                    'ETAS_DROneDayMd295', 'ETAS_DROneDayPPEMd2',
                                                                    'K3Md2', 'ETAS_HW_K3_AVERAGE_Md2'])
ETAS_mendo, ETAS_DROneDayMd2_mendo, ETAS_HWMd3_mendo, ETAS_DROneDayMd295_mendo, ETAS_DROneDayPPEMd2_mendo, K3Md2_mendo, ETAS_HW_K3_AVERAGE_Md2_mendo = (
    m_dfs['ETAS'], m_dfs['ETAS_DROneDayMd2'], m_dfs['ETAS_HWMd3'], m_dfs['ETAS_DROneDayMd295'],
    m_dfs['ETAS_DROneDayPPEMd2'], m_dfs['K3Md2'], m_dfs['ETAS_HW_K3_AVERAGE_Md2'])
ETAS_mendo_plow95, ETAS_mendo_phigh95 = m_plow['ETAS'], m_phigh['ETAS']
ETAS_DROneDayMd2_mendo_plow95, ETAS_DROneDayMd2_mendo_phigh95 = m_plow['ETAS_DROneDayMd2'], m_phigh['ETAS_DROneDayMd2']
ETAS_HWMd3_mendo_plow95, ETAS_HWMd3_mendo_phigh95 = m_plow['ETAS_HWMd3'], m_phigh['ETAS_HWMd3']
ETAS_DROneDayMd295_mendo_plow95, ETAS_DROneDayMd295_mendo_phigh95 = m_plow['ETAS_DROneDayMd295'], m_phigh['ETAS_DROneDayMd295']
ETAS_DROneDayPPEMd2_mendo_plow95, ETAS_DROneDayPPEMd2_mendo_phigh95 = m_plow['ETAS_DROneDayPPEMd2'], m_phigh['ETAS_DROneDayPPEMd2']
K3Md2_mendo_plow95, K3Md2_mendo_phigh95 = m_plow['K3Md2'], m_phigh['K3Md2']
ETAS_HW_K3_AVERAGE_Md2_mendo_plow95, ETAS_HW_K3_AVERAGE_Md2_mendo_phigh95 = m_plow['ETAS_HW_K3_AVERAGE_Md2'], m_phigh['ETAS_HW_K3_AVERAGE_Md2']

# Napa
n_dfs, n_plow, n_phigh = prep_sequence('2014-08-20', '2014-09-08', ['ETAS', 'STEPJAVA', 'ETAS_DROneDayMd2',
                                                                    'ETAS_HWMd3', 'ETAS_DROneDayMd295',
                                                                    'ETAS_DROneDayPPEMd2', 'K3Md2',
                                                                    'ETAS_HW_K3_AVERAGE_Md2'])

ETAS_napa, STEPJAVA_napa, ETAS_DROneDayMd2_napa, ETAS_HWMd3_napa, ETAS_DROneDayMd295_napa, ETAS_DROneDayPPEMd2_napa, K3Md2_napa, ETAS_HW_K3_AVERAGE_Md2_napa  = (
    n_dfs['ETAS'], n_dfs['STEPJAVA'], n_dfs['ETAS_DROneDayMd2'],
    n_dfs['ETAS_HWMd3'], n_dfs['ETAS_DROneDayMd295'], n_dfs['ETAS_DROneDayPPEMd2'],
    n_dfs['K3Md2'], n_dfs['ETAS_HW_K3_AVERAGE_Md2'])
ETAS_napa_plow95, ETAS_napa_phigh95 = n_plow['ETAS'], n_phigh['ETAS']
STEPJAVA_napa_plow95, STEPJAVA_napa_phigh95 = n_plow['STEPJAVA'], n_phigh['STEPJAVA']
ETAS_DROneDayMd2_napa_plow95, ETAS_DROneDayMd2_napa_phigh95 = n_plow['ETAS_DROneDayMd2'], n_phigh['ETAS_DROneDayMd2']
ETAS_HWMd3_napa_plow95, ETAS_HWMd3_napa_phigh95 = n_plow['ETAS_HWMd3'], n_phigh['ETAS_HWMd3']
ETAS_DROneDayMd295_napa_plow95, ETAS_DROneDayMd295_napa_phigh95 = n_plow['ETAS_DROneDayMd295'], n_phigh['ETAS_DROneDayMd295']
ETAS_DROneDayPPEMd2_napa_plow95, ETAS_DROneDayPPEMd2_napa_phigh95 = n_plow['ETAS_DROneDayPPEMd2'], n_phigh['ETAS_DROneDayPPEMd2']
K3Md2_napa_plow95, K3Md2_napa_phigh95 = n_plow['K3Md2'], n_phigh['K3Md2']
ETAS_HW_K3_AVERAGE_Md2_napa_plow95, ETAS_HW_K3_AVERAGE_Md2_napa_phigh95 = n_plow['ETAS_HW_K3_AVERAGE_Md2'], n_phigh['ETAS_HW_K3_AVERAGE_Md2']

# Quiet
q_dfs, q_plow, q_phigh = prep_sequence('2017-12-31', '2018-01-19', ['ETAS', 'STEPJAVA', 'ETAS_DROneDayMd2',
                                                                    'ETAS_HWMd3', 'ETAS_DROneDayMd295',
                                                                    'ETAS_DROneDayPPEMd2', 'K3Md2',
                                                                    'ETAS_HW_K3_AVERAGE_Md2', 'ETASSYN_DROneDayMd295'])
ETAS_quiet, STEPJAVA_quiet, ETAS_DROneDayMd2_quiet, ETAS_HWMd3_quiet, ETAS_DROneDayMd295_quiet, ETAS_DROneDayPPEMd2_quiet, K3Md2_quiet, ETAS_HW_K3_AVERAGE_Md2_quiet, ETASSYN_DROneDayMd295_quiet = (
    q_dfs['ETAS'], q_dfs['STEPJAVA'], q_dfs['ETAS_DROneDayMd2'],
    q_dfs['ETAS_HWMd3'], q_dfs['ETAS_DROneDayMd295'], q_dfs['ETAS_DROneDayPPEMd2'],
    q_dfs['K3Md2'], q_dfs['ETAS_HW_K3_AVERAGE_Md2'], q_dfs['ETASSYN_DROneDayMd295'])
ETAS_quiet_plow95, ETAS_quiet_phigh95 = q_plow['ETAS'], q_phigh['ETAS']
STEPJAVA_quiet_plow95, STEPJAVA_quiet_phigh95 = q_plow['STEPJAVA'], q_phigh['STEPJAVA']
ETAS_DROneDayMd2_quiet_plow95, ETAS_DROneDayMd2_quiet_phigh95 = q_plow['ETAS_DROneDayMd2'], q_phigh['ETAS_DROneDayMd2']
ETAS_HWMd3_quiet_plow95, ETAS_HWMd3_quiet_phigh95 = q_plow['ETAS_HWMd3'], q_phigh['ETAS_HWMd3']
ETAS_DROneDayMd295_quiet_plow95, ETAS_DROneDayMd295_quiet_phigh95 = q_plow['ETAS_DROneDayMd295'], q_phigh['ETAS_DROneDayMd295']
ETAS_DROneDayPPEMd2_quiet_plow95, ETAS_DROneDayPPEMd2_quiet_phigh95 = q_plow['ETAS_DROneDayPPEMd2'], q_phigh['ETAS_DROneDayPPEMd2']
K3Md2_quiet_plow95, K3Md2_quiet_phigh95 = q_plow['K3Md2'], q_phigh['K3Md2']
ETAS_HW_K3_AVERAGE_Md2_quiet_plow95, ETAS_HW_K3_AVERAGE_Md2_quiet_phigh95 = q_plow['ETAS_HW_K3_AVERAGE_Md2'], q_phigh['ETAS_HW_K3_AVERAGE_Md2']
ETASSYN_DROneDayMd295_quiet_plow95, ETASSYN_DROneDayMd295_quiet_phigh95 = q_plow['ETASSYN_DROneDayMd295'], q_phigh['ETASSYN_DROneDayMd295']


ETAS_dsquantile = np.genfromtxt('preprocessed_inputs/ETAS/ETAS_daily_space_quantiles.dat', delimiter='\t')
ETAS_DROneDayMd2_dsquantile = np.genfromtxt('preprocessed_inputs/ETAS_DROneDayMd2/ETAS_DROneDayMd2_daily_space_quantiles.dat', delimiter='\t')
ETAS_HWMd3_dsquantile = np.genfromtxt('preprocessed_inputs/ETAS_HWMd3/ETAS_HWMd3_daily_space_quantiles.dat', delimiter='\t')
ETAS_DROneDayMd295_dsquantile = np.genfromtxt('preprocessed_inputs/ETAS_DROneDayMd295/ETAS_DROneDayMd295_daily_space_quantiles.dat', delimiter='\t')
ETASSYN_DROneDayMd295_dsquantile = np.genfromtxt('preprocessed_inputs/ETASSYN_DROneDayMd295/ETASSYN_DROneDayMd295_daily_space_quantiles.dat', delimiter='\t')

STEP_dsquantile = np.genfromtxt('preprocessed_inputs/STEP/STEP_daily_space_quantiles.dat', delimiter='\t')
STEPJAVA_dsquantile = np.genfromtxt('preprocessed_inputs/STEPJAVA/STEPJAVA_daily_space_quantiles.dat', delimiter='\t')

ETAS_DROneDayPPEMd2_dsquantile = np.genfromtxt('preprocessed_inputs/ETAS_DROneDayPPEMd2/ETAS_DROneDayPPEMd2_daily_space_quantiles.dat', delimiter='\t')
K3Md2_dsquantile = np.genfromtxt('preprocessed_inputs/K3Md2/K3Md2_daily_space_quantiles.dat', delimiter='\t')
ETAS_HW_K3_AVERAGE_Md2_dsquantile = np.genfromtxt('preprocessed_inputs/ETAS_HW_K3_AVERAGE_Md2/ETAS_HW_K3_AVERAGE_Md2_daily_space_quantiles_updated.dat', delimiter='\t')

ETAS_dmquantile = np.genfromtxt('preprocessed_inputs/ETAS/ETAS_daily_magnitude_quantiles.dat', delimiter='\t')
ETAS_DROneDayMd2_dmquantile = np.genfromtxt('preprocessed_inputs/ETAS_DROneDayMd2/ETAS_DROneDayMd2_daily_magnitude_quantiles.dat', delimiter='\t')
ETAS_HWMd3_dmquantile = np.genfromtxt('preprocessed_inputs/ETAS_HWMd3/ETAS_HWMd3_daily_magnitude_quantiles.dat', delimiter='\t')
ETAS_DROneDayMd295_dmquantile = np.genfromtxt('preprocessed_inputs/ETAS_DROneDayMd295/ETAS_DROneDayMd295_daily_magnitude_quantiles.dat', delimiter='\t')
ETASSYN_DROneDayMd295_dmquantile = np.genfromtxt('preprocessed_inputs/ETASSYN_DROneDayMd295/ETASSYN_DROneDayMd295_daily_magnitude_quantiles.dat', delimiter='\t')

STEP_dmquantile = np.genfromtxt('preprocessed_inputs/STEP/STEP_daily_magnitude_quantiles.dat', delimiter='\t')
STEPJAVA_dmquantile = np.genfromtxt('preprocessed_inputs/STEPJAVA/STEPJAVA_daily_magnitude_quantiles.dat', delimiter='\t')

ETAS_DROneDayPPEMd2_dmquantile = np.genfromtxt('preprocessed_inputs/ETAS_DROneDayPPEMd2/ETAS_DROneDayPPEMd2_daily_magnitude_quantiles.dat', delimiter='\t')
K3Md2_dmquantile = np.genfromtxt('preprocessed_inputs/K3Md2/K3Md2_daily_magnitude_quantiles.dat', delimiter='\t')
ETAS_HW_K3_AVERAGE_Md2_dmquantile = np.genfromtxt('preprocessed_inputs/ETAS_HW_K3_AVERAGE_Md2/ETAS_HW_K3_AVERAGE_Md2_daily_magnitude_quantiles.dat', delimiter='\t')

catalogueETAS_dates = []
for i in range(len(catalogue.data)):
        catalogueETAS_dates.append(datetime(catalogue.get_datetimes()[i].year,
                                                     catalogue.get_datetimes()[i].month,
                                                     catalogue.get_datetimes()[i].day))
catalogall_ETAS = pd.DataFrame()
catalogall_ETAS['dates'] = catalogueETAS_dates

ETAS_alldates = pd.DataFrame()
ETAS_alldates['dates'] = forecast_dates['ETAS']
ETAS_alldates['squantiles'] = ETAS_dsquantile
ETAS_alldates['mquantiles'] = ETAS_dmquantile

catalogueSTEP_dates = []
for i in range(len(catalogue_STEP.data)):
        catalogueSTEP_dates.append(datetime(catalogue_STEP.get_datetimes()[i].year,
                                                     catalogue_STEP.get_datetimes()[i].month,
                                                     catalogue_STEP.get_datetimes()[i].day))
catalogall_STEP = pd.DataFrame()
catalogall_STEP['dates'] = catalogueSTEP_dates

STEP_alldates = pd.DataFrame()
STEP_alldates['dates'] = forecast_dates['STEP']
STEP_alldates['squantiles'] = STEP_dsquantile
STEP_alldates['mquantiles'] = STEP_dmquantile

catalogueSTEPJAVA_dates = []
for i in range(len(catalogue_STEPJAVA.data)):
        catalogueSTEPJAVA_dates.append(datetime(catalogue_STEPJAVA.get_datetimes()[i].year,
                                                         catalogue_STEPJAVA.get_datetimes()[i].month,
                                                         catalogue_STEPJAVA.get_datetimes()[i].day))
catalogall_STEPJAVA = pd.DataFrame()
catalogall_STEPJAVA['dates'] = catalogueSTEPJAVA_dates

STEPJAVA_alldates = pd.DataFrame()
STEPJAVA_alldates['dates'] = forecast_dates['STEPJAVA']
STEPJAVA_alldates['squantiles'] = STEPJAVA_dsquantile
STEPJAVA_alldates['mquantiles'] = STEPJAVA_dmquantile

ETAS_DROneDayMd2_alldates = pd.DataFrame()
ETAS_DROneDayMd2_alldates['dates'] = forecast_dates['ETAS-DROneDayMd2']
ETAS_DROneDayMd2_alldates['squantiles'] = ETAS_DROneDayMd2_dsquantile
ETAS_DROneDayMd2_alldates['mquantiles'] = ETAS_DROneDayMd2_dmquantile

ETAS_DROneDayPPEMd2_alldates = pd.DataFrame()
ETAS_DROneDayPPEMd2_alldates['dates'] = forecast_dates['ETAS-DROneDayPPEMd2']
ETAS_DROneDayPPEMd2_alldates['squantiles'] = ETAS_DROneDayPPEMd2_dsquantile
ETAS_DROneDayPPEMd2_alldates['mquantiles'] = ETAS_DROneDayPPEMd2_dmquantile

# Construct catalogall_ETAS_DROneDayMd2
catalogueETAS_DROneDayMd2_dates = []
for i in range(len(catalogue_ETAS_DROneDayMd2.data)):
        catalogueETAS_DROneDayMd2_dates.append(datetime(catalogue_ETAS_DROneDayMd2.get_datetimes()[i].year,
                                                                 catalogue_ETAS_DROneDayMd2.get_datetimes()[i].month,
                                                                 catalogue_ETAS_DROneDayMd2.get_datetimes()[i].day))
catalogall_ETAS_DROneDayMd2 = pd.DataFrame()
catalogall_ETAS_DROneDayMd2['dates'] = catalogueETAS_DROneDayMd2_dates

# Construct catalogall_ETAS_DROneDayPPEMd2
catalogueETAS_DROneDayPPEMd2_dates = []
for i in range(len(catalogue_ETAS_DROneDayPPEMd2.data)):
        catalogueETAS_DROneDayPPEMd2_dates.append(datetime(catalogue_ETAS_DROneDayPPEMd2.get_datetimes()[i].year,
                                                                    catalogue_ETAS_DROneDayPPEMd2.get_datetimes()[i].month,
                                                                    catalogue_ETAS_DROneDayPPEMd2.get_datetimes()[i].day))
catalogall_ETAS_DROneDayPPEMd2 = pd.DataFrame()
catalogall_ETAS_DROneDayPPEMd2['dates'] = catalogueETAS_DROneDayPPEMd2_dates

# Construct catalogall_ETAS_HWMd3
catalogueETAS_HWMd3_dates = []
for i in range(len(catalogue_ETAS_HWMd3.data)):
        catalogueETAS_HWMd3_dates.append(datetime(catalogue_ETAS_HWMd3.get_datetimes()[i].year,
                                                           catalogue_ETAS_HWMd3.get_datetimes()[i].month,
                                                           catalogue_ETAS_HWMd3.get_datetimes()[i].day))
catalogall_ETAS_HWMd3 = pd.DataFrame()
catalogall_ETAS_HWMd3['dates'] = catalogueETAS_HWMd3_dates

ETAS_HWMd3_alldates = pd.DataFrame()
ETAS_HWMd3_alldates['dates'] = forecast_dates['ETAS-HWMd3']
ETAS_HWMd3_alldates['squantiles'] = ETAS_HWMd3_dsquantile
ETAS_HWMd3_alldates['mquantiles'] = ETAS_HWMd3_dmquantile

ETAS_HW_K3_AVERAGE_Md2_alldates = pd.DataFrame()
ETAS_HW_K3_AVERAGE_Md2_alldates['dates'] = forecast_dates['ETAS-HW-K3-AVERAGE-Md2']
ETAS_HW_K3_AVERAGE_Md2_alldates['squantiles'] = ETAS_HW_K3_AVERAGE_Md2_dsquantile
ETAS_HW_K3_AVERAGE_Md2_alldates['mquantiles'] = ETAS_HW_K3_AVERAGE_Md2_dmquantile

K3Md2_alldates = pd.DataFrame()
K3Md2_alldates['dates'] = forecast_dates['K3Md2']
K3Md2_alldates['squantiles'] = K3Md2_dsquantile
K3Md2_alldates['mquantiles'] = K3Md2_dmquantile

catalogueETAS_DROneDayMd295_dates = []
for i in range(len(catalogue_ETAS_DROneDayMd295.data)):
        catalogueETAS_DROneDayMd295_dates.append(datetime(catalogue_ETAS_DROneDayMd295.get_datetimes()[i].year,
                                                                   catalogue_ETAS_DROneDayMd295.get_datetimes()[i].month,
                                                                   catalogue_ETAS_DROneDayMd295.get_datetimes()[i].day))
catalogall_ETAS_DROneDayMd295 = pd.DataFrame()
catalogall_ETAS_DROneDayMd295['dates'] = catalogueETAS_DROneDayMd295_dates

ETAS_DROneDayMd295_alldates = pd.DataFrame()
ETAS_DROneDayMd295_alldates['dates'] = forecast_dates['ETAS-DROneDayMd2.95']
ETAS_DROneDayMd295_alldates['squantiles'] = ETAS_DROneDayMd295_dsquantile
ETAS_DROneDayMd295_alldates['mquantiles'] = ETAS_DROneDayMd295_dmquantile

ETASSYN_DROneDayMd295_alldates = pd.DataFrame()
ETASSYN_DROneDayMd295_alldates['dates'] = forecast_dates['ETASSYN-DROneDayMd2.95']
ETASSYN_DROneDayMd295_alldates['squantiles'] = ETASSYN_DROneDayMd295_dsquantile
ETASSYN_DROneDayMd295_alldates['mquantiles'] = ETASSYN_DROneDayMd295_dmquantile

ETAS_actidates = pd.merge(catalogall_ETAS, ETAS_alldates,  how="inner", on="dates")
ETAS_DROneDayMd2_actidates = pd.merge(catalogall_ETAS_DROneDayMd2, ETAS_DROneDayMd2_alldates,  how="inner", on="dates")
ETAS_HWMd3_actidates = pd.merge(catalogall_ETAS_HWMd3, ETAS_HWMd3_alldates,  how="inner", on="dates")
ETAS_DROneDayMd295_actidates = pd.merge(catalogall_ETAS_DROneDayMd295, ETAS_DROneDayMd295_alldates,  how="inner", on="dates")
ETASSYN_DROneDayMd295_actidates = pd.merge(catalogall_ETAS_DROneDayMd295, ETASSYN_DROneDayMd295_alldates,  how="inner", on="dates")

STEP_actidates = pd.merge(catalogall_STEP, STEP_alldates,  how="inner", on="dates")
STEPJAVA_actidates = pd.merge(catalogall_STEPJAVA, STEPJAVA_alldates,  how="inner", on="dates")

ETAS_DROneDayPPEMd2_actidates = pd.merge(catalogall_ETAS_DROneDayPPEMd2, ETAS_DROneDayPPEMd2_alldates,  how="inner", on="dates")
K3Md2_actidates = pd.merge(catalogall_ETAS_HWMd3, K3Md2_alldates,  how="inner", on="dates")
ETAS_HW_K3_AVERAGE_Md2_actidates = pd.merge(catalogall_ETAS_HWMd3, ETAS_HW_K3_AVERAGE_Md2_alldates,  how="inner", on="dates")


########################################### data prep for magnitude test
percentile = 95.0



ETAS_cummag = np.genfromtxt('preprocessed_inputs/ETAS/ETAS_magnitude_counts.dat', delimiter='\t')
ETAS_DROneDayMd2_cummag = np.genfromtxt('preprocessed_inputs/ETAS_DROneDayMd2/ETAS_DROneDayMd2_magnitude_counts.dat', delimiter='\t')
ETAS_HWMd3_cummag = np.genfromtxt('preprocessed_inputs/ETAS_HWMd3/ETAS_HWMd3_magnitude_counts.dat', delimiter='\t')
ETAS_DROneDayMd295_cummag = np.genfromtxt('preprocessed_inputs/ETAS_DROneDayMd295/ETAS_DROneDayMd295_magnitude_counts.dat', delimiter='\t')
ETASSYN_DROneDayMd295_cummag = np.genfromtxt('preprocessed_inputs/ETASSYN_DROneDayMd295/ETASSYN_DROneDayMd295_magnitude_counts.dat', delimiter='\t')

STEP_cummag = np.genfromtxt('preprocessed_inputs/STEP/STEP_magnitude_counts.dat', delimiter='\t')
STEPJAVA_cummag = np.genfromtxt('preprocessed_inputs/STEPJAVA/STEPJAVA_magnitude_counts.dat', delimiter='\t')

ETAS_DROneDayPPEMd2_cummag = np.genfromtxt('preprocessed_inputs/ETAS_DROneDayPPEMd2/ETAS_DROneDayPPEMd2_magnitude_counts.dat', delimiter='\t')

K3Md2_cummag = np.genfromtxt('preprocessed_inputs/K3Md2/K3Md2_magnitude_counts.dat', delimiter='\t')
ETAS_HW_K3_AVERAGE_Md2_cummag = np.genfromtxt('preprocessed_inputs/ETAS_HW_K3_AVERAGE_Md2/ETAS_HW_K3_AVERAGE_Md2_magnitude_counts.dat', delimiter='\t')

ETAS_mtest = magnitude_test(ETAS_cummag, catalogue.magnitude_counts())
ETAS_DROneDayMd2_mtest = magnitude_test(ETAS_DROneDayMd2_cummag, catalogue_ETAS_DROneDayMd2.magnitude_counts())
ETAS_HWMd3_mtest = magnitude_test(ETAS_HWMd3_cummag, catalogue_ETAS_HWMd3.magnitude_counts())
ETAS_DROneDayMd295_mtest = magnitude_test(ETAS_DROneDayMd295_cummag, catalogue_ETAS_DROneDayMd295.magnitude_counts())

STEP_mtest = magnitude_test(STEP_cummag, catalogue_STEP.magnitude_counts())
STEPJAVA_mtest = magnitude_test(STEPJAVA_cummag, catalogue_STEPJAVA.magnitude_counts())

ETAS_DROneDayPPEMd2_mtest = magnitude_test(ETAS_DROneDayPPEMd2_cummag, catalogue_ETAS_DROneDayPPEMd2.magnitude_counts())
K3Md2_mtest = magnitude_test(K3Md2_cummag, catalogue_K3Md2.magnitude_counts())
ETAS_HW_K3_AVERAGE_Md2_mtest = magnitude_test(ETAS_HW_K3_AVERAGE_Md2_cummag, catalogue_ETAS_HW_K3_AVERAGE_Md2.magnitude_counts())


ETAS_cummag_nor = []
for i in range(len(ETAS_cummag)):
    ETAS_cummag_nor.append(ETAS_cummag[i] * (catalogue.event_count / sum(ETAS_ncounts)))

ETAS_DROneDayMd2_cummag_nor = []
for i in range(len(ETAS_DROneDayMd2_cummag)):
    ETAS_DROneDayMd2_cummag_nor.append(ETAS_DROneDayMd2_cummag[i] * (catalogue_ETAS_DROneDayMd2.event_count / sum(ETAS_DROneDayMd2_ncounts)))

ETAS_HWMd3_cummag_nor = []
for i in range(len(ETAS_HWMd3_cummag)):
    ETAS_HWMd3_cummag_nor.append(ETAS_HWMd3_cummag[i] * (catalogue_ETAS_HWMd3.event_count / sum(ETAS_HWMd3_ncounts)))

ETAS_DROneDayMd295_cummag_nor = []
for i in range(len(ETAS_DROneDayMd295_cummag)):
    ETAS_DROneDayMd295_cummag_nor.append(ETAS_DROneDayMd295_cummag[i] * (catalogue_ETAS_DROneDayMd295.event_count / sum(ETAS_DROneDayMd295_ncounts)))

ETASSYN_DROneDayMd295_cummag_nor = []
for i in range(len(ETASSYN_DROneDayMd295_cummag)):
    ETASSYN_DROneDayMd295_cummag_nor.append(ETASSYN_DROneDayMd295_cummag[i] * (catalogue_ETAS_DROneDayMd295.event_count / sum(ETASSYN_DROneDayMd295_ncounts)))

STEP_cummag_nor = []
for i in range(len(STEP_cummag)):
    STEP_cummag_nor.append(STEP_cummag[i] * (catalogue_STEP.event_count / sum(STEP_ncounts)))

STEPJAVA_cummag_nor = []
for i in range(len(STEPJAVA_cummag)):
    STEPJAVA_cummag_nor.append(STEPJAVA_cummag[i] * (catalogue_STEPJAVA.event_count / sum(STEPJAVA_ncounts)))

ETAS_DROneDayPPEMd2_cummag_nor = []
for i in range(len(ETAS_DROneDayPPEMd2_cummag)):
    ETAS_DROneDayPPEMd2_cummag_nor.append(ETAS_DROneDayPPEMd2_cummag[i] * (catalogue_ETAS_DROneDayPPEMd2.event_count / sum(ETAS_DROneDayPPEMd2_ncounts)))

K3Md2_cummag_nor = []
for i in range(len(K3Md2_cummag)):
    K3Md2_cummag_nor.append(K3Md2_cummag[i] * (catalogue_K3Md2.event_count / sum(K3Md2_ncounts)))


ETAS_HW_K3_AVERAGE_Md2_cummag_nor = []
for i in range(len(ETAS_HW_K3_AVERAGE_Md2_cummag)):
    ETAS_HW_K3_AVERAGE_Md2_cummag_nor.append(ETAS_HW_K3_AVERAGE_Md2_cummag[i] * (catalogue_ETAS_HW_K3_AVERAGE_Md2.event_count / sum(ETAS_HW_K3_AVERAGE_Md2_ncounts)))


kstest_ETASm = calculate_pvalues(catalogue, ETAS_cummag_nor)
kstest_ETAS_DROneDayMd2m = calculate_pvalues(catalogue_ETAS_DROneDayMd2, ETAS_DROneDayMd2_cummag_nor)
kstest_ETAS_HWMd3m = calculate_pvalues(catalogue_ETAS_HWMd3, ETAS_HWMd3_cummag_nor)
kstest_ETAS_DROneDayMd295m = calculate_pvalues(catalogue_ETAS_DROneDayMd295, ETAS_DROneDayMd295_cummag_nor)

kstest_STEPm = calculate_pvalues(catalogue_STEP, STEP_cummag_nor)
kstest_STEPJAVAm = calculate_pvalues(catalogue_STEPJAVA, STEPJAVA_cummag_nor)

kstest_ETAS_DROneDayPPEMd2m = calculate_pvalues(catalogue_ETAS_DROneDayPPEMd2, ETAS_DROneDayPPEMd2_cummag_nor)
kstest_K3Md2m = calculate_pvalues(catalogue_K3Md2, K3Md2_cummag_nor)
kstest_ETAS_HW_K3_AVERAGE_Md2m = calculate_pvalues(catalogue_ETAS_HW_K3_AVERAGE_Md2, ETAS_HW_K3_AVERAGE_Md2_cummag_nor)

ETAS_cummag_low = []
ETAS_cummag_high = []

ETAS_DROneDayMd2_cummag_low = []
ETAS_DROneDayMd2_cummag_high = []

ETAS_HWMd3_cummag_low = []
ETAS_HWMd3_cummag_high = []

ETAS_DROneDayMd295_cummag_low = []
ETAS_DROneDayMd295_cummag_high = []

ETASSYN_DROneDayMd295_cummag_low = []
ETASSYN_DROneDayMd295_cummag_high = []

STEP_cummag_low = []
STEP_cummag_high = []

STEPJAVA_cummag_low = []
STEPJAVA_cummag_high = []

ETAS_DROneDayPPEMd2_cummag_low = []
ETAS_DROneDayPPEMd2_cummag_high = []

K3Md2_cummag_low = []
K3Md2_cummag_high = []

ETAS_HW_K3_AVERAGE_Md2_cummag_low = []
ETAS_HW_K3_AVERAGE_Md2_cummag_high = []

for i in range(len(ETAS_cummag)):
    ETAS_cummag_low.append(scipy.stats.poisson.ppf((1 - percentile/100.)/2., ETAS_cummag_nor[i]))
    ETAS_cummag_high.append(scipy.stats.poisson.ppf(1 - (1 - percentile/100.)/2., ETAS_cummag_nor[i]))

    ETAS_DROneDayMd2_cummag_low.append(scipy.stats.poisson.ppf((1 - percentile/100.)/2., ETAS_DROneDayMd2_cummag_nor[i]))
    ETAS_DROneDayMd2_cummag_high.append(scipy.stats.poisson.ppf(1 - (1 - percentile/100.)/2., ETAS_DROneDayMd2_cummag_nor[i]))

    ETAS_HWMd3_cummag_low.append(scipy.stats.poisson.ppf((1 - percentile/100.)/2., ETAS_HWMd3_cummag_nor[i]))
    ETAS_HWMd3_cummag_high.append(scipy.stats.poisson.ppf(1 - (1 - percentile/100.)/2., ETAS_HWMd3_cummag_nor[i]))

    ETAS_DROneDayMd295_cummag_low.append(scipy.stats.poisson.ppf((1 - percentile/100.)/2., ETAS_DROneDayMd295_cummag_nor[i]))
    ETAS_DROneDayMd295_cummag_high.append(scipy.stats.poisson.ppf(1 - (1 - percentile/100.)/2., ETAS_DROneDayMd295_cummag_nor[i]))

    ETASSYN_DROneDayMd295_cummag_low.append(scipy.stats.poisson.ppf((1 - percentile/100.)/2., ETASSYN_DROneDayMd295_cummag_nor[i]))
    ETASSYN_DROneDayMd295_cummag_high.append(scipy.stats.poisson.ppf(1 - (1 - percentile/100.)/2., ETASSYN_DROneDayMd295_cummag_nor[i]))

    STEP_cummag_low.append(scipy.stats.poisson.ppf((1 - percentile/100.)/2., STEP_cummag_nor[i]))
    STEP_cummag_high.append(scipy.stats.poisson.ppf(1 - (1 - percentile/100.)/2., STEP_cummag_nor[i]))

    STEPJAVA_cummag_low.append(scipy.stats.poisson.ppf((1 - percentile/100.)/2., STEPJAVA_cummag_nor[i]))
    STEPJAVA_cummag_high.append(scipy.stats.poisson.ppf(1 - (1 - percentile/100.)/2., STEPJAVA_cummag_nor[i]))

    ETAS_DROneDayPPEMd2_cummag_low.append(scipy.stats.poisson.ppf((1 - percentile/100.)/2., ETAS_DROneDayPPEMd2_cummag_nor[i]))
    ETAS_DROneDayPPEMd2_cummag_high.append(scipy.stats.poisson.ppf(1 - (1 - percentile/100.)/2., ETAS_DROneDayPPEMd2_cummag_nor[i]))

    K3Md2_cummag_low.append(scipy.stats.poisson.ppf((1 - percentile/100.)/2., K3Md2_cummag_nor[i]))
    K3Md2_cummag_high.append(scipy.stats.poisson.ppf(1 - (1 - percentile/100.)/2., K3Md2_cummag_nor[i]))

    ETAS_HW_K3_AVERAGE_Md2_cummag_low.append(scipy.stats.poisson.ppf((1 - percentile/100.)/2., ETAS_HW_K3_AVERAGE_Md2_cummag_nor[i]))
    ETAS_HW_K3_AVERAGE_Md2_cummag_high.append(scipy.stats.poisson.ppf(1 - (1 - percentile/100.)/2., ETAS_HW_K3_AVERAGE_Md2_cummag_nor[i]))



################################################################# preparing data for Information Gain
ETAS_joli = np.genfromtxt('preprocessed_inputs/ETAS/ETAS_joli.dat', delimiter='\t')
ETAS_DROneDayMd2_joli = np.genfromtxt('preprocessed_inputs/ETAS_DROneDayMd2/ETAS_DROneDayMd2_joli.dat', delimiter='\t')
ETAS_HWMd3_joli = np.genfromtxt('preprocessed_inputs/ETAS_HWMd3/ETAS_HWMd3_joli.dat', delimiter='\t')
ETAS_DROneDayMd295_joli = np.genfromtxt('preprocessed_inputs/ETAS_DROneDayMd295/ETAS_DROneDayMd295_joli.dat', delimiter='\t')
ETASSYN_DROneDayMd295_joli = np.genfromtxt('preprocessed_inputs/ETASSYN_DROneDayMd295/ETASSYN_DROneDayMd295_joli.dat', delimiter='\t')

STEP_joli = np.genfromtxt('preprocessed_inputs/STEP/STEP_joli_up.dat', delimiter='\t')
STEPJAVA_joli = np.genfromtxt('preprocessed_inputs/STEPJAVA/STEPJAVA_joli.dat', delimiter='\t')

ETAS_DROneDayPPEMd2_joli = np.genfromtxt('preprocessed_inputs/ETAS_DROneDayPPEMd2/ETAS_DROneDayPPEMd2_joli.dat', delimiter='\t')
K3Md2_joli = np.genfromtxt('preprocessed_inputs/K3Md2/K3Md2_joli.dat', delimiter='\t')
ETAS_HW_K3_AVERAGE_Md2_joli = np.genfromtxt('preprocessed_inputs/ETAS_HW_K3_AVERAGE_Md2/ETAS_HW_K3_AVERAGE_Md2_joli.dat', delimiter='\t')

ETAS['joli_ETAS'] = ETAS_joli
ETAS_DROneDayMd2['joli_ETAS_DROneDayMd2'] = ETAS_DROneDayMd2_joli
ETAS_HWMd3['joli_ETAS_HWMd3'] = ETAS_HWMd3_joli
ETAS_DROneDayMd295['joli_ETAS_DROneDayMd295'] = ETAS_DROneDayMd295_joli
ETASSYN_DROneDayMd295['joli_ETASSYN_DROneDayMd295'] = ETASSYN_DROneDayMd295_joli

STEP['joli_STEP'] = STEP_joli
STEPJAVA['joli_STEPJAVA'] = STEPJAVA_joli
HKJ_STEP = pd.DataFrame()
HKJ_STEP['date'] = list(STEP.date[:])
# HKJ_STEP['joli_HKJ_STEP'] = STEPJAVA_joli
ETAS_DROneDayPPEMd2['joli_ETAS_DROneDayPPEMd2'] = ETAS_DROneDayPPEMd2_joli
K3Md2['joli_K3Md2'] = K3Md2_joli
ETAS_HW_K3_AVERAGE_Md2['joli_ETAS_HW_K3_Md2'] = ETAS_HW_K3_AVERAGE_Md2_joli

periods = [
    ('2007-08-01', '2009-01-01'),
    ('2009-01-01', '2010-09-01'),
    ('2010-09-01', '2012-07-01'),
    ('2012-07-01', '2012-10-01'),
    ('2013-01-21', '2016-07-01'),
    ('2016-10-01', '2018-07-01')
]

# Define the base models needed for the main panels (1 to 6)
base_models_per_period = [
    [ETAS, STEP],
    [ETAS, STEP],
    [ETAS, STEP, STEPJAVA],
    [ETAS, STEP],
    [ETAS, ETAS_DROneDayMd2, ETAS_HWMd3, ETAS_HW_K3_AVERAGE_Md2, ETAS_DROneDayPPEMd2, K3Md2],
    [ETAS, ETAS_DROneDayMd2, ETAS_HWMd3, ETAS_DROneDayMd295, ETASSYN_DROneDayMd295, ETAS_DROneDayPPEMd2]
]

jolis = []
joli_dates_list = []
tmps = []
tmp_dates_list = []

for i, (start, end) in enumerate(periods):
    period_dfs = []
    for df in base_models_per_period[i]:
        # Filter by date range
        mask = (df['date'] >= start) & (df['date'] < end) if i < 5 else (df['date'] >= start) & (df['date'] <= '2018-06-30')
        sliced_df = df[mask].copy()

        cols_to_keep = ['date'] + [col for col in sliced_df.columns if col.startswith('joli_') or col.startswith('n_')]
        period_dfs.append(sliced_df[cols_to_keep])

    # Merge all base models for this period
    merged_joli = period_dfs[0]
    for df in period_dfs[1:]:
        merged_joli = pd.merge(merged_joli, df, how="inner", on="date")

    jolis.append(merged_joli)
    joli_dates_list.append([datetime.strptime(d, '%Y-%m-%d') for d in merged_joli.date])

joli_1, joli_2, joli_3, joli_4, joli_5, joli_6 = jolis
joli_1dates, joli_2dates, joli_3dates, joli_4dates, joli_5dates, joli_6dates = joli_dates_list
