# GENERATED by scripts/build_era_lite.py from notebooks/era_candidate_causal.ipynb -- DO NOT EDIT.
# Edit the FULL notebook, then re-run the build script (see its docstring for the sync workflow).
"""Frozen ERA scaffold: utils + plotting + baseline loading,
extracted verbatim from the full notebook's cells 2-4."""
import sys
import os
import importlib
import numpy as np
import csep
import matplotlib.pyplot as plt
import gc
import pandas as pd
from typing import Tuple
import tempfile
import h5py
import calendar
import re
from csep import load_gridded_forecast
from csep.core.catalogs import AbstractBaseCatalog
from csep.utils.time_utils import datetime_to_utc_epoch
from csep.core.forecasts import GriddedForecast
from datetime import datetime, timedelta, timezone
from typing import Iterator, Tuple, Any, Optional
from joblib import Parallel, delayed
import scipy.stats
import copy
import matplotlib
import matplotlib.font_manager as fm
import datetime
import pickle
import cartopy.crs as ccrs
import cartopy
from cartopy.io import img_tiles
import matplotlib.ticker as mticker
from cartopy.mpl.gridliner import LONGITUDE_FORMATTER, LATITUDE_FORMATTER
import seaborn as sns
import shapefile
from csep.models import Polygon
from matplotlib import gridspec
from csep.models import EvaluationResult
import scipy
from csep.utils import time_utils
from csep.core import poisson_evaluations as poisson
from csep.utils.stats import poisson_joint_log_likelihood_ndarray
from typing import Optional, Union, Sequence, Any, Tuple, List
from csep.core import binomial_evaluations as binomial
from csep.core import catalogs
from csep.utils import plots
from matplotlib.dates import AutoDateLocator, DateFormatter
from mpl_toolkits.axes_grid1 import make_axes_locatable
import scipy.stats as stats
import math
from csep.core.regions import CartesianGrid2D
from matplotlib.ticker import FormatStrFormatter
import geopandas as gpd
import logging
from datetime import datetime, timezone
import urllib.request
import csep.utils.time_utils
import numpy
from typing import Any
import traceback
import matplotlib.ticker as ticker
import csep.utils.plots as csep_plots
import csep.core.poisson_evaluations
from scipy.stats import poisson as poisson_stat
import warnings

import numpy as np
if not hasattr(np, 'trapz'):      # NumPy >= 2.0
    np.trapz = np.trapezoid


# ===== utils (full notebook cell 2: defs) =====
def query_comcat_chunked(start_time, end_time, min_mag=1.0, chunk_years=1) -> csep.core.catalogs.CSEPCatalog:
    # print(f"Querying ComCat in resilient chunked intervals (M>={min_mag})...")
    import time

    current_start = pd.to_datetime(start_time, utc=True)
    target_end    = pd.to_datetime(end_time, utc=True)
    all_catalogs = []

    while current_start < target_end:
        current_end = current_start + pd.DateOffset(years=chunk_years)
        if current_end > target_end:
            current_end = target_end

        # Defensive 3-tier retry loop for network stability
        for retry in range(3):
            try:
                chunk_cat = csep.query_comcat(
                    start_time=csep.utils.time_utils.strptime_to_utc_datetime(str(current_start)),
                    end_time=csep.utils.time_utils.strptime_to_utc_datetime(str(current_end)),
                    min_magnitude=min_mag
                )
                all_catalogs.append(chunk_cat)
                break
            except Exception as e:
                if retry == 2:
                    raise e
                print(f"    Network warning: chunk fetch failed ({e}). Retrying in 3s...")
                time.sleep(3.0)

        current_start = current_end
        time.sleep(0.5) # Strategic sleep delay to completely prevent triggering firewall limits

    if not all_catalogs:
        raise ValueError("No earthquake data retrieved from chunked query pipeline.")

    combined_data = np.concatenate([np.asarray(cat.catalog) for cat in all_catalogs])

    unified_cat = csep.core.catalogs.CSEPCatalog(
        data=combined_data,
        name='comcat_chunked_unified',
        compute_stats=True
    )
    unified_cat.update_catalog_stats()
    return unified_cat

def _make_catalog_view(
    full_catalog: AbstractBaseCatalog,
    start_idx: int,
    end_idx: int,
    name_suffix: str,
) -> AbstractBaseCatalog:
    """
    Create a new catalog object that wraps a *view* of full_catalog.catalog[start_idx:end_idx].

    This avoids copying event data: slicing a numpy structured array with [start:end]
    returns a view, and AbstractBaseCatalog will keep that as-is.

    We copy metadata (filename, catalog_id, filters, etc.) from full_catalog.
    """
    # Clamp indices to valid range
    n = full_catalog.get_number_of_events()
    start_idx = max(0, min(int(start_idx), n))
    end_idx = max(0, min(int(end_idx), n))
    if end_idx < start_idx:
        end_idx = start_idx

    view = full_catalog.catalog[start_idx:end_idx]  # view, not copy

    cls = full_catalog.__class__
    base_name = full_catalog.name or ""
    name = f"{base_name}_{name_suffix}" if base_name else name_suffix

    # Construct a new catalog of the same class, wrapping the view
    cat = cls(
        filename=full_catalog.filename,
        data=view,
        catalog_id=full_catalog.catalog_id,
        format=full_catalog.format,
        name=name,
        compute_stats=True,
        filters=full_catalog.filters,
        metadata=full_catalog.metadata,
        date_accessed=full_catalog.date_accessed,
    )
    return cat

def build_daily_csep_series(
    full_catalog: AbstractBaseCatalog,
    region,
    train_start,
    train_end,
    test_start,
    test_end,
) -> Tuple[pd.Series, pd.Series, pd.Series, pd.Series]:
    """
    Build daily CSEP catalog Series for train/test splits using view-based slicing.

    Notes
    -----
    This function intentionally does not require or apply a space–magnitude
    `region`. It returns lightweight CSEP catalog views (slices of
    `full_catalog.catalog`) for history and daily target periods. Assigning a
    `region` and any spatial filtering should be performed later by the model
    wrapper (or caller) if desired. This keeps this utility memory- and
    computation-friendly.

    Parameters
    ----------
    full_catalog : AbstractBaseCatalog
        Long CSEP catalog covering the entire period of interest. Must be sorted
        by origin_time (as PyCSEP normally guarantees).
    train_start, train_end : datetime-like
        Training period [train_start, train_end), i.e., train_end is *exclusive*.
    test_start, test_end : datetime-like
        Test period [test_start, test_end), test_end is *exclusive*.

    Returns
    -------
    train_x : pd.Series
        Index: training day starts (UTC-normalised pandas Timestamps).
        Values: CSEP catalogs (view-based) containing *all events before that day* (history).
    train_y : pd.Series
        Index: training day starts.
        Values: CSEP catalogs (view-based) containing events in [day, day+1d).
    test_x : pd.Series
        Index: test day starts.
        Values: CSEP catalogs (view-based) for history days (events before that day).
    test_y : pd.Series
        Index: test day starts.
        Values: CSEP catalogs (view-based) for daily target periods (events in [day, day+1d)).
    """
    # Normalise times to UTC Timestamps
    train_start = pd.to_datetime(train_start, utc=True)
    train_end   = pd.to_datetime(train_end,   utc=True)
    test_start  = pd.to_datetime(test_start,  utc=True)
    test_end    = pd.to_datetime(test_end,    utc=True)

    # Global time bounds we care about
    broad_start = train_start
    broad_end   = test_end

    # Epoch times for all events (sorted)
    times = full_catalog.get_epoch_times()
    if times is None or len(times) == 0:
        # No events at all: return empty Series with the right indices
        train_days = pd.date_range(train_start.normalize(), train_end.normalize(),
                                   freq="D", tz="UTC", inclusive="left")
        test_days = pd.date_range(test_start.normalize(), test_end.normalize(),
                                  freq="D", tz="UTC", inclusive="left")
        empty_train = pd.Series({d: _make_catalog_view(full_catalog, 0, 0, f"empty_train_{i}")
                                 for i, d in enumerate(train_days)}, name="train_empty")
        empty_test = pd.Series({d: _make_catalog_view(full_catalog, 0, 0, f"empty_test_{i}")
                                for i, d in enumerate(test_days)}, name="test_empty")
        # Use empties for all four, to keep shapes consistent
        return empty_train, empty_train.copy(), empty_test, empty_test.copy()

    # Convert broad window to epoch millis
    broad_start_ms = int(datetime_to_utc_epoch(broad_start))
    broad_end_ms   = int(datetime_to_utc_epoch(broad_end))

    # Indices for the broad window [broad_start, broad_end)
    global_start_idx = int(np.searchsorted(times, broad_start_ms, side="left"))
    global_end_idx   = int(np.searchsorted(times, broad_end_ms,   side="left"))

    # Day grids: [start, end) half-open intervals
    train_days = pd.date_range(
        train_start.normalize(),
        train_end.normalize(),
        freq="D",
        tz="UTC",
        inclusive="left",
    )
    test_days = pd.date_range(
        test_start.normalize(),
        test_end.normalize(),
        freq="D",
        tz="UTC",
        inclusive="left",
    )

    train_x_dict = {}
    train_y_dict = {}
    test_x_dict  = {}
    test_y_dict  = {}

    # --- Build train_x / train_y ------------------------------------------------
    for i, day_start in enumerate(train_days):
        day_end = day_start + pd.Timedelta(days=1)

        day_start_ms = int(datetime_to_utc_epoch(day_start))
        day_end_ms   = int(datetime_to_utc_epoch(day_end))

        # History: all events in [broad_start, day_start)
        hist_start_idx = global_start_idx
        hist_end_idx   = int(np.searchsorted(times, day_start_ms, side="left"))

        # Target: events in [day_start, day_end)
        targ_start_idx = hist_end_idx
        targ_end_idx   = int(np.searchsorted(times, day_end_ms, side="left"))

        hist_cat = _make_catalog_view(
            full_catalog,
            start_idx=hist_start_idx,
            end_idx=hist_end_idx,
            name_suffix=f"train_hist_{i}",
        )
        day_cat = _make_catalog_view(
            full_catalog,
            start_idx=targ_start_idx,
            end_idx=targ_end_idx,
            name_suffix=f"train_day_{i}",
        )

        day_cat.region = region

        magnitude_bins = region.magnitudes

        # filter magnitude above minimum magnitude bin
        day_cat.filter(f"magnitude >= {magnitude_bins[0]}", in_place=True)

        train_x_dict[day_start] = hist_cat
        train_y_dict[day_start] = day_cat

    # --- Build test_x / test_y -------------------------------------------------
    for j, day_start in enumerate(test_days):
        day_end = day_start + pd.Timedelta(days=1)

        day_start_ms = int(datetime_to_utc_epoch(day_start))
        day_end_ms   = int(datetime_to_utc_epoch(day_end))

        hist_start_idx = global_start_idx
        hist_end_idx   = int(np.searchsorted(times, day_start_ms, side="left"))

        targ_start_idx = hist_end_idx
        targ_end_idx   = int(np.searchsorted(times, day_end_ms, side="left"))

        hist_cat = _make_catalog_view(
            full_catalog,
            start_idx=hist_start_idx,
            end_idx=hist_end_idx,
            name_suffix=f"test_hist_{j}",
        )
        day_cat = _make_catalog_view(
            full_catalog,
            start_idx=targ_start_idx,
            end_idx=targ_end_idx,
            name_suffix=f"test_day_{j}",
        )

        day_cat.region = region

        magnitude_bins = region.magnitudes

        # filter magnitude above minimum magnitude bin
        day_cat.filter(f"magnitude >= {magnitude_bins[0]}", in_place=True)

        test_x_dict[day_start] = hist_cat
        test_y_dict[day_start] = day_cat

    train_x = pd.Series(train_x_dict, name="train_history")
    train_y = pd.Series(train_y_dict, name="train_daily")
    test_x  = pd.Series(test_x_dict,  name="test_history")
    test_y  = pd.Series(test_y_dict,  name="test_daily")

    return train_x, train_y, test_x, test_y

def _number_test_ndarray(fore_cnt, obs_cnt, epsilon=1e-6):
    """ Computes delta1 and delta2 values from the csep1 number test.

    Args:
        fore_cnt (float): parameter of poisson distribution coming from expected value of the forecast
        obs_cnt (float): count of earthquakes observed during the testing period.
        epsilon (float): tolerance level to satisfy the requirements of two-sided p-value

    Returns
        result (tuple): (delta1, delta2)
    """
    delta1 = 1.0 - scipy.stats.poisson.cdf(obs_cnt - epsilon, fore_cnt)
    delta2 = scipy.stats.poisson.cdf(obs_cnt + epsilon, fore_cnt)
    return delta1, delta2

def number_test(forecast, observed_catalog):
    """Computes "N-Test" on a gridded forecast.
    author: @asim

    Computes Number (N) test for Observed and Forecasts. Both data sets are expected to be in terms of event counts.
    We find the Total number of events in Observed Catalog and Forecasted Catalogs. Which are then employed to compute the probablities of
    (i) At least no. of events (delta 1)
    (ii) At most no. of events (delta 2) assuming the poissonian distribution.

    Args:
        observation: Observed (Gridded) seismicity (Numpy Array):
                    An Observation has to be Number of Events in Each Bin
                    It has to be a either zero or positive integer only (No Floating Point)
        forecast:   Forecast of a Model (Gridded) (Numpy Array)
                    A forecast has to be in terms of Average Number of Events in Each Bin
                    It can be anything greater than zero

    Returns:
        out (tuple): (delta_1, delta_2)
    """
    result = EvaluationResult()

    # observed count
    obs_cnt = observed_catalog.event_count

    # forecasts provide the expected number of events during the time horizon of the forecast
    fore_cnt = np.float64(sum(forecast))

    epsilon = 1e-6

    # stores the actual result of the number test
    delta1, delta2 = _number_test_ndarray(fore_cnt, obs_cnt, epsilon=epsilon)

    # store results
    result.test_distribution = ('poisson', fore_cnt)
    result.name = 'Poisson N-Test'
    result.observed_statistic = obs_cnt
    result.quantile = (delta1, delta2)
    result.status = 'normal'
    result.min_mw = 3.95

    return result

def compute_binary_spatial_quantiles(forecast_series, obs_series, num_sims=10000):
    """
    Computes the spatial quantiles (zeta) using the CSEP binary spatial test.
    """
    zetas = []

    for dt in forecast_series.index:
        fc = forecast_series.loc[dt]
        obs = obs_series.loc[dt]

        # 1. Expected rate per cell
        data = np.asarray(fc.data, dtype=float)
        if data.ndim > 1:
            lam_spatial = data.sum(axis=1)
        else:
            n_cells = fc.region.num_nodes
            n_mag = len(data) // n_cells
            lam_spatial = data.reshape(n_cells, n_mag).sum(axis=1)

        total_lam = lam_spatial.sum()
        if total_lam <= 0:
            continue

        # 2. Observed activated cells
        lons = obs.get_longitudes()
        lats = obs.get_latitudes()
        if len(lons) == 0:
            continue

        c_obs = np.zeros(fc.region.num_nodes)
        try:
            idxs = fc.region.get_index_of(lons, lats)
            for idx in idxs:
                if idx >= 0 and idx < fc.region.num_nodes:
                    c_obs[idx] = 1
        except Exception:
            continue

        n_act = int(c_obs.sum())
        if n_act == 0:
            continue

        # Normalize lambda to match number of activated cells
        lam_norm = lam_spatial * (n_act / total_lam)

        # Log probabilities
        p_1 = 1.0 - np.exp(-lam_norm)
        p_1 = np.clip(p_1, 1e-10, 1.0)
        log_p1 = np.log(p_1)
        log_p0 = -lam_norm

        # Observed jBILL
        jBILL_obs = np.sum(c_obs * log_p1 + (1 - c_obs) * log_p0)

        # Simulate catalogs consistent with n_act
        p_draw = lam_spatial / total_lam
        non_zero_cells = np.sum(p_draw > 0)
        if non_zero_cells < n_act:
            continue

        log_p1_p0 = log_p1 - log_p0
        base_jBILL = np.sum(log_p0)

        sim_jBILLs = np.zeros(num_sims)
        for i in range(num_sims):
            sim_idxs = np.random.choice(fc.region.num_nodes, size=n_act, replace=False, p=p_draw)
            sim_jBILLs[i] = base_jBILL + np.sum(log_p1_p0[sim_idxs])

        zeta = np.sum(sim_jBILLs <= jBILL_obs) / num_sims
        zetas.append(zeta)

    return np.array(zetas)

def _poisson_likelihood_test(forecast_data, observed_data, num_simulations=10000, random_numbers=None,
                             seed=None, use_observed_counts=True, verbose=True, normalize_likelihood=False):
    """
	Computes the likelihood-test from CSEP using an efficient simulation based approach.
	Args:
	    forecast_data (numpy.ndarray): nd array where [:, -1] are the magnitude bins.
	    observed_data (numpy.ndarray): same format as observation.
	    num_simulations: default number of simulations to use for likelihood based simulations
    	seed: used for reproducibility of the prng
	    random_numbers (numpy.ndarray): can supply an explicit list of random numbers, primarily used for software testing
	    use_observed_counts (bool): if true, will simulate catalogs using the observed events, if false will draw from poisson distribution
	    verbose (bool): if true, write progress of test to command line
	    normalize_likelihood (bool): if true, normalize likelihood. used by default for magnitude and spatial tests
	"""

    # set seed for the likelihood test
    if seed is not None:
        numpy.random.seed(seed)

    # used to determine where simulated earthquake should be placed, by definition of cumsum these are sorted
    # float64 REQUIRED for the sampling CDF: with float32 forecasts the
    # normalised cumulative weights can top out below 1.0 and searchsorted
    # overruns the last cell (observed on causal_jrect_hm15b)
    forecast_data = numpy.asarray(forecast_data, dtype=numpy.float64)
    sampling_weights = numpy.cumsum(forecast_data.ravel()) / numpy.sum(forecast_data)

    # data structures to store results
    sim_fore = numpy.zeros(sampling_weights.shape)
    simulated_ll = []

    # properties of observations and forecasts
    n_obs = numpy.sum(observed_data)
    n_fore = numpy.sum(forecast_data)

    expected_forecast_count = numpy.sum(forecast_data)
    log_bin_expectations = numpy.log(forecast_data.ravel())
    # used for conditional-likelihood, magnitude, and spatial tests to normalize the rate-component of the forecasts
    if use_observed_counts and normalize_likelihood:
        scale = n_obs / n_fore
        expected_forecast_count = int(n_obs)
        log_bin_expectations = numpy.log(forecast_data.ravel() * scale)

    # gets the 1d indices to bins that contain target events, these indexes perform copies and not views into the array
    target_idx = numpy.nonzero(observed_data.ravel())

    # note for performance: these operations perform copies
    observed_data_nonzero = observed_data.ravel()[target_idx]
    target_event_forecast = log_bin_expectations[target_idx] * observed_data_nonzero

    # main simulation step in this loop
    for idx in range(num_simulations):
        if use_observed_counts:
            num_events_to_simulate = int(n_obs)
        else:
            num_events_to_simulate = int(numpy.random.poisson(expected_forecast_count))

        if random_numbers is None:
            sim_fore = _simulate_catalog(num_events_to_simulate, sampling_weights, sim_fore)
        else:
            sim_fore = _simulate_catalog(num_events_to_simulate, sampling_weights, sim_fore,
                                         random_numbers=random_numbers[idx, :])

        # compute joint log-likelihood from simulation by leveraging that only cells with target events contribute to likelihood
        sim_target_idx = numpy.nonzero(sim_fore)
        sim_obs_nonzero = sim_fore[sim_target_idx]
        sim_target_event_forecast = log_bin_expectations[sim_target_idx] * sim_obs_nonzero

        # compute joint log-likelihood
        current_ll = poisson_joint_log_likelihood_ndarray(sim_target_event_forecast, sim_obs_nonzero,
                                                          expected_forecast_count)

        # append to list of simulated log-likelihoods
        simulated_ll.append(current_ll)

        # just be verbose
        if verbose:
            if (idx + 1) % 100 == 0:
                print(f'... {idx + 1} catalogs simulated.')

    # observed joint log-likelihood
    obs_ll = poisson_joint_log_likelihood_ndarray(target_event_forecast, observed_data_nonzero, expected_forecast_count)

    # quantile score
    qs = numpy.sum(simulated_ll <= obs_ll) / num_simulations

    # float, float, list
    return qs, obs_ll, simulated_ll

def magnitude_test(gridded_forecast_mags, gridded_catalog_mags, num_simulations=10000, seed=None, random_numbers=None,
                   verbose=False):
    """
    Performs the Magnitude Test on a Gridded Forecast using an observed catalog.

    Note: The forecast and the observations should be scaled to the same time period before calling this function. This increases
    transparency as no assumptions are being made about the length of the forecasts. This is particularly important for
    gridded forecasts that supply their forecasts as rates.

    Args:
        gridded_forecast: csep.core.forecasts.GriddedForecast
        observed_catalog: csep.core.catalogs.Catalog
        num_simulations (int): number of simulations used to compute the quantile score
        seed (int): used fore reproducibility, and testing
        random_numbers (numpy.ndarray): random numbers used to override the random number generation. injection point for testing.

    Returns:
        evaluation_result: csep.core.evaluations.EvaluationResult
    """

    # simply call likelihood test on catalog data and forecast
    qs, obs_ll, simulated_ll = _poisson_likelihood_test(gridded_forecast_mags, gridded_catalog_mags,
                                                        num_simulations=num_simulations,
                                                        seed=seed,
                                                        random_numbers=random_numbers,
                                                        use_observed_counts=True,
                                                        verbose=verbose,
                                                        normalize_likelihood=True)

    # populate result data structure
    result = EvaluationResult()
    result.test_distribution = simulated_ll
    result.name = 'Poisson M-Test'
    result.observed_statistic = obs_ll
    result.quantile = qs
    result.status = 'normal'
    return result

def calculate_pvalues(obs_catalog, fmd_pred, magfive=False):
    pbinned_prob = []
    obinned_prob = []

    if magfive == False:
        for i in range(len(fmd_pred)):
            pbinned_prob.append(fmd_pred[i] / obs_catalog.event_count)
            obinned_prob.append((obs_catalog.magnitude_counts()[i] / obs_catalog.event_count))
    else:
        for i in range(len(fmd_pred)):
            pbinned_prob.append(fmd_pred[i] / obs_catalog.event_count)
            obinned_prob.append((obs_catalog.magnitude_counts()[10:][i] / obs_catalog.event_count))

    cum_obs_fmd = np.cumsum(obinned_prob)
    cum_pred_fmd = np.cumsum(pbinned_prob)

    diff_fmds = []
    for i in range(len(cum_obs_fmd)):
        diff_fmds.append(np.abs(cum_obs_fmd[i] - cum_pred_fmd[i]))

    D = max(diff_fmds)

    Neff = obs_catalog.event_count / 2.0

    z = D * np.sqrt(Neff)

    p = []
    for i in range(1, 1000):
        p.append((-1.0)**(i-1.0) * np.exp(-2.0*i**2.0 * z**2.0))

    pv = 2.0 * sum(p)

    return pv

def _simulate_catalog(num_events, sampling_weights, sim_fore, random_numbers=None):

    # generate uniformly distributed random numbers in [0,1), this
    if random_numbers is None:
        random_numbers = numpy.random.rand(num_events)
    else:
        # TODO: ensure that random numbers are all between 0 and 1.
        pass

    # reset simulation array to zero, but don't reallocate
    sim_fore.fill(0)

    # find insertion points using binary search inserting to satisfy a[i-1] <= v < a[i]
    pnts = numpy.searchsorted(sampling_weights, random_numbers, side='right')

    # create simulated catalog by adding to the original locations
    numpy.add.at(sim_fore, pnts, 1)
    assert sim_fore.sum() == num_events, "simulated the wrong number of events!"

    return sim_fore

def compute_ll_model(lam_model: np.ndarray, n_obs: np.ndarray, eps: float) -> float:
    """
    Computes the Poisson Log-Likelihood for the candidate model.
    LL_model = sum(n_obs * log(lambda_model) - lambda_model)
    """
    # Rate floor: prevent ̈ = 0 → log(0). float64 so the metric is exact
    # regardless of the (float32) storage dtype of the forecast series.
    lam_model = np.maximum(np.asarray(lam_model, dtype=np.float64), eps)
    epsilon = 1e-9

    return (n_obs * np.log(lam_model + epsilon) - lam_model).sum()

def evaluate_fn(
    test_y: pd.Series,
    forecasts: pd.Series,
    ll_etas_series: pd.Series,
    config: dict[str, Any],
) -> float:
    """
    Evaluate candidate AutoML forecasts using *Poisson log-likelihood difference*
    relative to an ETAS baseline model.

    For each day t, and each (space, magnitude) cell i:
        lambda_model = expected count from model forecast
        lambda_etas  = expected count from ETAS baseline
        n_obs        = observed count in test_y for that cell

    Daily LL:
        LL_model = sum_i [ n_obs * log(lambda_model) - lambda_model ]
        LL_etas  = sum_i [ n_obs * log(lambda_etas)  - lambda_etas  ]

    We return the mean daily LL difference:
        score = mean_t (LL_model(t) - LL_etas(t))

    Positive score means the AutoML model outperforms ETAS.

    Config options:
        eps          : minimum rate floor to avoid log(0)                  (default 1e-10)
        per_event    : if True, divide daily LL by total events t          (default False)
        plot         : if True, plot cumulative LL and log daily counts    (default False)
        count_eps    : rate floor used for log(count) plotting             (default 1e-6)
        check_region : if True, assert geometry consistency first          (default True)
        plot_detailed: if True, full sets of plots will be generated otherwise only 2 main plots (default False)

    Returns:
        float — mean daily LL difference (model − ETAS).
    """
    # 1. Align forecasts and test_y
    if not forecasts.index.equals(test_y.index):
        # Force alignment if they differ
        common_idx = forecasts.index.intersection(test_y.index)
        if len(common_idx) == 0:
             raise ValueError("No overlapping dates between forecasts and test_y")
        forecasts = forecasts.loc[common_idx]
        test_y = test_y.loc[common_idx]

    # 2. Check overlap with pre-computed ETAS
    missing_dates = test_y.index.difference(ll_etas_series.index)
    if len(missing_dates) > 0:
        print(f"Warning: Dropping {len(missing_dates)} days from evaluation because they are missing from the ETAS baseline file.")
        print(f"Missing Dates: {missing_dates[:]}...")

        # Filter test_y and forecasts to only what exists in ll_etas_series
        valid_dates = test_y.index.intersection(ll_etas_series.index)
        if len(valid_dates) == 0:
             raise ValueError("No common dates found between test data and ETAS baseline file.")

        test_y = test_y.loc[valid_dates]
        forecasts = forecasts.loc[valid_dates]

    # Setup data for combined plotting
    plot_configs = {
        'ETAS': (ETAS_ncounts, 0, '#FFA500'),
        'ETAS-DROneDayMd2': (ETAS_DROneDayMd2_ncounts, catalogue.event_count - 188, '#6a3d9a'),
        'ETAS-HWMd3': (ETAS_HWMd3_ncounts, catalogue.event_count - 188, '#e31a1c'),
        'ETAS-DROneDayMd295': (ETAS_DROneDayMd295_ncounts, catalogue.event_count - catalogue_ETAS_DROneDayMd295.event_count, '#fb9a99'),
        'STEP': (STEP_ncounts, 0, '#15B01A'),
        'STEPJAVA': (STEPJAVA_ncounts, 248.0, '#C79FEF'),
        'ETAS-DROneDayPPEMd2': (ETAS_DROneDayPPEMd2_ncounts, catalogue.event_count - 188, '#00FFFF'),
        'K3Md2': (K3Md2_ncounts, catalogue.event_count - 188, 'dodgerblue'),
        'ETAS-HW-K3-AVERAGE-Md2': (ETAS_HW_K3_AVERAGE_Md2_ncounts, catalogue.event_count - 188, '#708090'),
        'ETASSYN-DROneDayMd295': (ETASSYN_DROneDayMd295_ncounts, catalogue.event_count - catalogue_ETASSYN_DROneDayMd295.event_count, 'brown')
    }
    model_dates = [d for d in forecasts.index]
    model_counts = [np.sum(fc.data) for fc in forecasts]

    eps = float(config.get("eps", 1e-10))
    count_eps = float(config.get("count_eps", 1e-6))
    plot = bool(config.get("plot", False))
    plot_detailed = bool(config.get("plot_detailed", False))

    daily_scores: list[float] = []
    total_events = 0
    daily_counts_model: list[float] = []
    daily_counts_obs: list[float] = []
    eval_dates: list[pd.Timestamp] = []
    event_times: list[pd.Timestamp] = []
    event_mags: list[float] = []

    for day in forecasts.index:
        fc_model = forecasts.loc[day]
        obs_cat  = test_y.loc[day]
        ll_etas  = ll_etas_series.loc[day]

        if not isinstance(fc_model, GriddedForecast):
            raise TypeError(f"Forecast for {day} is not a GriddedForecast.")

        lam_model = np.asarray(fc_model.data, float)
        n_obs     = np.asarray(obs_cat.spatial_magnitude_counts(), float)

        # --- Shape Alignment ---
        if lam_model.shape[1] == n_obs.shape[1] + 1:
            lam_model = lam_model[:, :-1]
        elif lam_model.shape[1] + 1 == n_obs.shape[1]:
            n_obs = n_obs[:, :-1]

        if lam_model.shape != n_obs.shape:
            min_mags = min(lam_model.shape[1], n_obs.shape[1])
            lam_model = lam_model[:, :min_mags]
            n_obs = n_obs[:, :min_mags]

        total_events += np.sum(n_obs)
        daily_counts_model.append(float(np.sum(lam_model)))
        daily_counts_obs.append(float(np.sum(n_obs)))
        eval_dates.append(day)

        # Collect per-event times/magnitudes for scatter overlay
        try:
            times = getattr(obs_cat, "get_epoch_times", lambda: [])()
            mags = getattr(obs_cat, "get_magnitudes", lambda: [])()
            if len(times) and len(mags):
                event_times.extend(pd.to_datetime(times, unit="ms", utc=True))
                event_mags.extend(np.asarray(mags, float))
        except Exception:
            print(f"Warning: Could not extract event times/magnitudes for day {day}.")
        ll_model = compute_ll_model(lam_model, n_obs, eps)
        daily_scores.append(ll_model - ll_etas)

    if plot and len(daily_scores) > 0:
        # Names the plot path inherits from the pre-causal notebook
        # generation: the aligned series ARE this function's arguments, and
        # the region-filtered full catalog arrives via config (captured in
        # the EVALUATOR closure -- the notebook global is deleted for
        # namespace hygiene).
        forecasts_aligned = forecasts
        test_y_aligned = test_y
        full_region_cat = config["full_region_cat"]
        plot_cumulative_scores(eval_dates, daily_scores, daily_counts_model, daily_counts_obs, total_events, event_times, event_mags)

        # Pre-compute agg_forecasts
        # float64 aggregate: this feeds pyCSEP's own consistency tests,
        # whose sampling CDFs require it (see _poisson_likelihood_test)
        data_array = np.zeros(forecasts[forecasts.index[0]].data.shape,
                              dtype=np.float64)
        for day in forecasts.index[0:]:
            data_array += forecasts[day].data

        region = forecasts[forecasts.index[0]].region
        mags = forecasts[forecasts.index[0]].magnitudes

        agg_forecasts = GriddedForecast(
            data=data_array,
            region=region,
            magnitudes=mags,
            start_time=forecasts.index[0],
            end_time=forecasts.index[-1] + pd.Timedelta(days=1)
        )

        if plot_detailed:
            plot_configs = {
                'ETAS': (ETAS_ncounts, 0, '#FFA500'),
                'ETAS-DROneDayMd2': (ETAS_DROneDayMd2_ncounts, catalogue.event_count - 188, '#6a3d9a'),
                'ETAS-HWMd3': (ETAS_HWMd3_ncounts, catalogue.event_count - 188, '#e31a1c'),
                'ETAS-DROneDayMd2.95': (ETAS_DROneDayMd295_ncounts, catalogue.event_count - catalogue_ETAS_DROneDayMd295.event_count, '#fb9a99'),
                'STEP': (STEP_ncounts, 0, '#15B01A'),
                'STEPJAVA': (STEPJAVA_ncounts, 248.0, '#C79FEF'),
                'ETAS-DROneDayPPEMd2': (ETAS_DROneDayPPEMd2_ncounts, catalogue.event_count - 188, '#00FFFF'),
                'K3Md2': (K3Md2_ncounts, catalogue.event_count - 188, 'dodgerblue'),
                'ETAS-HW-K3-AVERAGE-Md2': (ETAS_HW_K3_AVERAGE_Md2_ncounts, catalogue.event_count - 188, '#708090'),
                'ETASSYN-DROneDayMd2.95': (ETASSYN_DROneDayMd295_ncounts, catalogue.event_count - catalogue_ETASSYN_DROneDayMd295.event_count, 'brown')
            }

            # Extract model dates and counts
            model_dates = [d for d in forecasts.index]
            model_counts = [np.sum(fc.data) for fc in forecasts]
            # plot_cumulative_number_of_events_plus_all_benchmarks(model_dates, model_counts, catalogue, models_name, forecast_dates, plot_configs)
            # n_test_ax = plot_comparative_n_test_results(forecasts, catalogue, mags, agg_forecasts)

            start_epoch = pd.Timestamp(forecasts.index[0]).value // 10**6
            end_epoch = (pd.Timestamp(forecasts.index[-1]) + pd.Timedelta(days=1)).value // 10**6
            test_catalog = full_region_cat.filter([f'origin_time >= {start_epoch}', f'origin_time < {end_epoch}'])
            test_catalog = test_catalog.filter([f'magnitude >= {mags[0]}'])

            # --- Number Test ---
            number_test_result = csep.core.poisson_evaluations.number_test(agg_forecasts, test_catalog)
            ax = csep_plots.plot_consistency_test(number_test_result, plot_args={'xlabel': 'Number of events'})
            plt.show()

            # Generate the combined plot
            plot_combined_cumulative_and_n_test(
                model_dates,
                model_counts,
                catalogue,
                models_name,
                forecast_dates,
                plot_configs,
                forecasts,
                catalogue,
                mags,
                agg_forecasts
            )

            windows = [
                (pd.Timestamp('2010-01-06', tz='UTC'), pd.Timestamp('2010-01-26', tz='UTC')),
                (pd.Timestamp('2010-03-31', tz='UTC'), pd.Timestamp('2010-04-20', tz='UTC')),
                (pd.Timestamp('2012-08-22', tz='UTC'), pd.Timestamp('2012-09-11', tz='UTC')),
                (pd.Timestamp('2014-03-06', tz='UTC'), pd.Timestamp('2014-03-26', tz='UTC')),
                (pd.Timestamp('2014-08-20', tz='UTC'), pd.Timestamp('2014-09-09', tz='UTC')),
                (pd.Timestamp('2017-12-31', tz='UTC'), pd.Timestamp('2018-01-20', tz='UTC')),
            ]

            # Ensure variables are mapped correctly from previous evaluation runs
            model_dates = [d for d in forecasts_aligned.index]
            model_counts = [np.sum(fc.data) for fc in forecasts_aligned]

            for w_start, w_end in windows:
                plot_combined_cumulative_and_n_test(model_dates, model_counts, catalogue, models_name, forecast_dates, plot_configs, forecasts, full_region_cat, mags, agg_forecasts, window_start=w_start, window_end=w_end)

        plot_sequence_configs(eval_dates, daily_counts_model, daily_counts_obs, percentile)

        # --- Spatial Test ---
        args_forecast = {
                'title': f'Aggregated Forecast from {forecasts.index[0].date()} to {(forecasts.index[-1] + pd.Timedelta(days=1)).date()}',
                'grid_labels': False,
                'borders': False,
                'coastline': False,
                'basemap': None,
                'cmap': 'magma',
                'alpha_exp': 0.6,
                'clim':[-5, 0]
            }

        ax1 = agg_forecasts.plot(plot_args=args_forecast)
        plt.show()

        if not plot_detailed:
            start_epoch = pd.Timestamp(forecasts.index[0]).value // 10**6
            end_epoch = (pd.Timestamp(forecasts.index[-1]) + pd.Timedelta(days=1)).value // 10**6
            test_catalog = full_region_cat.filter([f'origin_time >= {start_epoch}', f'origin_time < {end_epoch}'])
            test_catalog = test_catalog.filter([f'magnitude >= {mags[0]}'])

        # poison spatial test
        spatial_test_result = csep.core.poisson_evaluations.spatial_test(agg_forecasts, test_catalog, seed=1, num_simulations=10000)
        ax = csep_plots.plot_consistency_test(spatial_test_result, plot_args={'xlabel': 'Normalised Spatial likelihood'})
        plt.show()

        # Computing spatial quantiles for Neural ETAS using CSEP binary spatial test.
        zetas_netas = compute_binary_spatial_quantiles(forecasts_aligned, test_y_aligned, num_sims=10000)
        # Extract the arrays directly to handle both DataFrames and pure NumPy arrays
        active_days_arrays = [
            ETAS_actidates.squantiles.values,
            ETAS_DROneDayMd2_actidates.squantiles.values,
            ETAS_HWMd3_actidates.squantiles.values,
            ETAS_DROneDayMd295_actidates.squantiles.values,
            STEP_actidates.squantiles.values,
            STEPJAVA_actidates.squantiles.values,
            ETAS_DROneDayPPEMd2_actidates.squantiles.values,
            K3Md2_actidates.squantiles.values,
            ETAS_HW_K3_AVERAGE_Md2_actidates.squantiles.values,
            zetas_netas  # The candidate model spatial quantiles
        ]

        model_names = [
            'ETAS', 'ETAS_DROneDayMd2', 'ETAS_HWMd3', 'ETAS_DROneDayMd295',
            'STEP', 'STEPJAVA',
            'ETAS_DROneDayPPEMd2',
            'K3Md2',
            'ETAS-HW-K3-AVERAGE-Md2',
            'Neural ETAS'
        ]

        plot_spatial_quantiles(active_days_arrays, model_names)


        # --- Magnitude Test ---
        mag_test_result = csep.core.poisson_evaluations.magnitude_test(agg_forecasts, test_catalog, seed=1, num_simulations=10000)
        ax = csep_plots.plot_consistency_test(mag_test_result, plot_args={'xlabel': 'Normalised likelihood'})
        plt.show()
        plot_magnitude_test(agg_forecasts, forecasts_aligned, full_region_cat=full_region_cat)


        # ----- Info Gain -------
        plot_information_gain(forecasts_aligned, test_y_aligned=test_y_aligned)


    if not daily_scores:
        return 0.0

    return float(np.sum(daily_scores) / len(forecasts.index))


# ===== plotting (full notebook cell 3: defs) =====
import numpy

def plot_cumulative_scores(eval_dates, daily_scores, daily_counts_model, daily_counts_obs, total_events, event_times, event_mags):
    # Cumulative LL difference + per-event magnitude scatter on twin axis (left)
    cum_scores = np.cumsum(daily_scores)
    cum_model = np.cumsum(daily_counts_model)
    cum_obs = np.cumsum(daily_counts_obs)

    fig_ll, (ax_ll, ax_cum) = plt.subplots(1, 2, figsize=(20, 6), gridspec_kw={'width_ratios': [1.1, 1.0]})
    ax_ll.plot(eval_dates, cum_scores, marker='o', linestyle='-')
    ax_ll.axhline(0, color='red', linestyle='--')
    ax_ll.set_title(f'Daily Information Gain (Model - ETAS), N={int(total_events)}')
    ax_ll.set_ylabel('Log-Likelihood Difference')
    ax_ll.grid()

    if len(event_times) > 0 and len(event_mags) > 0:
        ax_mag = ax_ll.twinx()
        z = (7.5**np.array(event_mags))*0.001
        ax_mag.scatter(event_times, event_mags, s=z, color='black', alpha=0.6, label=r'Observed $M \geq 3.95$ events')
        ax_mag.set_ylabel('Event Magnitude')
        ax_mag.legend(loc='upper left')

    forecast_upper  = np.array([poisson_stat.ppf(0.975, mu=lam) for lam in cum_model])
    forecast_lower  = np.array([poisson_stat.ppf(0.025, mu=lam) for lam in cum_model])

    ax_cum.step(eval_dates, cum_obs, linestyle='-', color='k', alpha=0.6, zorder=2, linewidth=3, where='mid', label='Observations')
    ax_cum.step(eval_dates, cum_model, linestyle='-', color='blue', alpha=0.6, zorder=2, linewidth=2, where='mid', label='Forecasts')
    ax_cum.vlines(eval_dates, ymin=forecast_lower, ymax=forecast_upper, color='tab:blue', alpha=0.05, label='95% Poisson CI')
    ax_cum.set_title('Cumulative Daily Event Counts')
    ax_cum.set_xlabel('Date')
    ax_cum.set_ylabel(r'Cumulative number of $\mathregular{M_w}\geq$ 3.95 earthquakes', fontsize=22)
    ax_cum.grid(axis="y", which='major', linestyle='--', linewidth=1, zorder=0)
    ax_cum.legend()

    fig_ll.tight_layout()
    plt.show()

def plot_sequence_configs(eval_dates, daily_counts_model, daily_counts_obs, percentile=95):
    dates_arr = pd.to_datetime(pd.Index(eval_dates), utc=True)
    fore_daily_count = np.asarray(daily_counts_model)
    obse_daily_count = np.asarray(daily_counts_obs)
    counts_model = np.asarray(daily_counts_model, float)
    counts_obs = np.asarray(daily_counts_obs, float)

    # Ferndale
    ferndale_cfgs = [
        {'df': ETAS_ferndale, 'n_col': 'n_ETAS', 'plow': ETAS_ferndale_plow95, 'phigh': ETAS_ferndale_phigh95, 'color': '#FFA500', 'label': 'ETAS'},
        {'df': STEP_ferndale, 'n_col': 'n_STEP', 'plow': STEP_ferndale_plow95, 'phigh': STEP_ferndale_phigh95, 'color': '#15B01A', 'label': 'STEP'}
    ]

    # Active
    active_cfgs = [
        {'df': ETAS_active, 'n_col': 'n_ETAS', 'plow': ETAS_active_plow95, 'phigh': ETAS_active_phigh95, 'color': '#FFA500', 'label': 'ETAS'},
        {'df': STEP_active, 'n_col': 'n_STEP', 'plow': STEP_active_plow95, 'phigh': STEP_active_phigh95, 'color': '#15B01A', 'label': 'STEP'}
    ]

    # Swarm
    swarm_cfgs = [
        {'df': ETAS_swarm, 'n_col': 'n_ETAS', 'plow': ETAS_swarm_plow95, 'phigh': ETAS_swarm_phigh95, 'color': '#FFA500', 'label': 'ETAS'},
        {'df': STEP_swarm, 'n_col': 'n_STEP', 'plow': STEP_swarm_plow95, 'phigh': STEP_swarm_phigh95, 'color': '#15B01A', 'label': 'STEP'},
    ]

    # Mendo
    mendo_cfgs = [
        {'df': ETAS_mendo, 'n_col': 'n_ETAS', 'plow': ETAS_mendo_plow95, 'phigh': ETAS_mendo_phigh95, 'color': '#FFA500', 'label': 'ETAS'},
        {'df': ETAS_DROneDayMd2_mendo, 'n_col': 'n_ETAS_DROneDayMd2', 'plow': ETAS_DROneDayMd2_mendo_plow95, 'phigh': ETAS_DROneDayMd2_mendo_phigh95, 'color': '#6a3d9a', 'label': 'ETAS-DROneDayMd2'},
        {'df': ETAS_HWMd3_mendo, 'n_col': 'n_ETAS_HWMd3', 'plow': ETAS_HWMd3_mendo_plow95, 'phigh': ETAS_HWMd3_mendo_phigh95, 'color': 'teal', 'label': 'ETAS-HWMd3'},
        {'df': ETAS_DROneDayMd295_mendo, 'n_col': 'n_ETAS_DROneDayMd295', 'plow': ETAS_DROneDayMd295_mendo_plow95, 'phigh': ETAS_DROneDayMd295_mendo_phigh95, 'color': '#fb9a99', 'label': 'ETAS_DROneDayMd2.95'},
        {'df': ETAS_DROneDayPPEMd2_mendo, 'n_col': 'n_ETAS_DROneDayPPEMd2', 'plow': ETAS_DROneDayPPEMd2_mendo_plow95, 'phigh': ETAS_DROneDayPPEMd2_mendo_phigh95, 'color': '#00FFFF', 'label': 'ETAS_DROneDayPPEMd2'},
        {'df': K3Md2_mendo, 'n_col': 'n_K3Md2', 'plow': K3Md2_mendo_plow95, 'phigh': K3Md2_mendo_phigh95, 'color': 'dodgerblue', 'label': 'K3Md2'},
        {'df': ETAS_HW_K3_AVERAGE_Md2_mendo, 'n_col': 'n_ETAS_HW_K3_AVERAGE_Md2', 'plow': ETAS_HW_K3_AVERAGE_Md2_mendo_plow95, 'phigh': ETAS_HW_K3_AVERAGE_Md2_mendo_phigh95, 'color': '#708090', 'label': 'ETAS_HW_K3_AVERAGE_Md2'}
        ]

    # Napa
    napa_cfgs = [
        {'df': ETAS_napa, 'n_col': 'n_ETAS', 'plow': ETAS_napa_plow95, 'phigh': ETAS_napa_phigh95, 'color': '#FFA500', 'label': 'ETAS'},
        {'df': STEPJAVA_napa, 'n_col': 'n_STEPJAVA', 'plow': STEPJAVA_napa_plow95, 'phigh': STEPJAVA_napa_phigh95, 'color': '#15B01A', 'label': 'STEPJAVA'},
        {'df': ETAS_DROneDayMd2_napa, 'n_col': 'n_ETAS_DROneDayMd2', 'plow': ETAS_DROneDayMd2_napa_plow95, 'phigh': ETAS_DROneDayMd2_napa_phigh95, 'color': '#6a3d9a', 'label': 'ETAS_DROneDayMd2'},
        {'df': ETAS_HWMd3_napa, 'n_col': 'n_ETAS_HWMd3', 'plow': ETAS_HWMd3_napa_plow95, 'phigh': ETAS_HWMd3_napa_phigh95, 'color': 'teal', 'label': 'ETAS_HWMd3'},
        {'df': ETAS_DROneDayMd295_napa, 'n_col': 'n_ETAS_DROneDayMd295', 'plow': ETAS_DROneDayMd295_napa_plow95, 'phigh': ETAS_DROneDayMd295_napa_phigh95, 'color': '#fb9a99', 'label': 'ETAS_DROneDayMd295'},
        {'df': ETAS_DROneDayPPEMd2_napa, 'n_col': 'n_ETAS_DROneDayPPEMd2', 'plow': ETAS_DROneDayPPEMd2_napa_plow95, 'phigh': ETAS_DROneDayPPEMd2_napa_phigh95, 'color': '#00FFFF', 'label': 'ETAS_DROneDayPPEMd2'},
        {'df': K3Md2_napa, 'n_col': 'n_K3Md2', 'plow': K3Md2_napa_plow95, 'phigh': K3Md2_napa_phigh95, 'color': 'dodgerblue', 'label': 'K3Md2'},
        {'df': ETAS_HW_K3_AVERAGE_Md2_napa, 'n_col': 'n_ETAS_HW_K3_AVERAGE_Md2', 'plow': ETAS_HW_K3_AVERAGE_Md2_napa_plow95, 'phigh': ETAS_HW_K3_AVERAGE_Md2_napa_phigh95, 'color': '#708090', 'label': 'ETAS_HW_K3_AVERAGE_Md2'},
        ]

    # Quiet
    quiet_cfgs = [
        {'df': ETAS_quiet, 'n_col': 'n_ETAS', 'plow': ETAS_quiet_plow95, 'phigh': ETAS_quiet_phigh95, 'color': '#FFA500', 'label': 'ETAS'},
        {'df': STEPJAVA_quiet, 'n_col': 'n_STEPJAVA', 'plow': STEPJAVA_quiet_plow95, 'phigh': STEPJAVA_quiet_phigh95, 'color': '#15B01A', 'label': 'STEPJAVA'},
        {'df': ETAS_DROneDayMd2_quiet, 'n_col': 'n_ETAS_DROneDayMd2', 'plow': ETAS_DROneDayMd2_quiet_plow95, 'phigh': ETAS_DROneDayMd2_quiet_phigh95, 'color': '#6a3d9a', 'label': 'ETAS_DROneDayMd2'},
        {'df': ETAS_HWMd3_quiet, 'n_col': 'n_ETAS_HWMd3', 'plow': ETAS_HWMd3_quiet_plow95, 'phigh': ETAS_HWMd3_quiet_phigh95, 'color': 'teal', 'label': 'ETAS_HWMd3'},
        {'df': ETAS_DROneDayMd295_quiet, 'n_col': 'n_ETAS_DROneDayMd295', 'plow': ETAS_DROneDayMd295_quiet_plow95, 'phigh': ETAS_DROneDayMd295_quiet_phigh95, 'color': '#fb9a99', 'label': 'ETAS_DROneDayMd295'},
        {'df': ETAS_DROneDayPPEMd2_quiet, 'n_col': 'n_ETAS_DROneDayPPEMd2', 'plow': ETAS_DROneDayPPEMd2_quiet_plow95, 'phigh': ETAS_DROneDayPPEMd2_quiet_phigh95, 'color': '#00FFFF', 'label': 'ETAS_DROneDayPPEMd2'},
        {'df': K3Md2_quiet, 'n_col': 'n_K3Md2', 'plow': K3Md2_quiet_plow95, 'phigh': K3Md2_quiet_phigh95, 'color': 'dodgerblue', 'label': 'K3Md2'},
        {'df': ETAS_HW_K3_AVERAGE_Md2_quiet, 'n_col': 'n_ETAS_HW_K3_AVERAGE_Md2', 'plow': ETAS_HW_K3_AVERAGE_Md2_quiet_plow95, 'phigh': ETAS_HW_K3_AVERAGE_Md2_quiet_phigh95, 'color': '#708090', 'label': 'ETAS_HW_K3_AVERAGE_Md2'},
        {'df': ETASSYN_DROneDayMd295_quiet, 'n_col': 'n_ETASSYN_DROneDayMd295', 'plow': ETASSYN_DROneDayMd295_quiet_plow95, 'phigh': ETASSYN_DROneDayMd295_quiet_phigh95, 'color': 'brown', 'label': 'ETASSYN-DROneDayMd2.95'},
        ]

    windows = [(pd.Timestamp('2010-01-06', tz='UTC'), pd.Timestamp('2010-01-26', tz='UTC')),
               (pd.Timestamp('2010-03-31', tz='UTC'), pd.Timestamp('2010-04-20', tz='UTC')),
               (pd.Timestamp('2012-08-22', tz='UTC'), pd.Timestamp('2012-09-11', tz='UTC')),
               (pd.Timestamp('2014-03-06', tz='UTC'), pd.Timestamp('2014-03-26', tz='UTC')),
               (pd.Timestamp('2014-08-20', tz='UTC'), pd.Timestamp('2014-09-09', tz='UTC')),
               (pd.Timestamp('2017-12-31', tz='UTC'), pd.Timestamp('2018-01-20', tz='UTC')),
               ]

    sequences = [ferndale_cfgs, active_cfgs, swarm_cfgs, mendo_cfgs, napa_cfgs, quiet_cfgs]

    if len(dates_arr) > 0:
        fig, axes = plt.subplots(len(windows), 2, figsize=(14, 5.5 * len(windows)), sharex=False)
        fig.tight_layout()
        axes_list = list(axes)

        for i, (w_start, w_end) in enumerate(windows):
            ax_pair = axes_list[i]
            ax_left, ax_right = ax_pair
            mask = (dates_arr >= w_start) & (dates_arr < w_end)
            if not np.any(mask): continue

            forecast_upper = np.array([scipy.stats.poisson.ppf(1 - (1 - percentile/100.)/2., np.float64(lam)) for lam in fore_daily_count[mask]])
            forecast_lower = np.array([scipy.stats.poisson.ppf((1 - percentile/100.)/2., np.float64(lam)) for lam in fore_daily_count[mask]])
            ax_left.fill_between(dates_arr[mask], forecast_lower, forecast_upper, linewidth=1.5, edgecolor='grey', facecolor='lightgrey', alpha=0.2, step='mid', zorder=1)
            ax_left.step(dates_arr[mask], fore_daily_count[mask], '-.', color='red', where='mid', linewidth=3, zorder=2, label='Neural ETAS')

            # Iterate over dates as well to match x and y dimensions
            for date, obs, forecast_low, forecast_up in zip(dates_arr[mask], obse_daily_count[mask], forecast_lower, forecast_upper):
                if obs >= forecast_low and obs <= forecast_up:
                    ax_left.plot(date, obs, 'o', markeredgecolor='k', color='white', markersize=18, alpha=0.7, zorder=2) # color='#4575b4',
                else:
                    ax_left.plot(date, obs, 'o', markeredgecolor='k', color='#d73027', markersize=18, alpha=0.7, zorder=2)

            ax_left.legend(fontsize=12, facecolor='whitesmoke', edgecolor='grey', loc='upper right')
            ax_left.axvline(x=w_start + pd.Timedelta(days=4), ymin=0 , ymax=5, c='k', linewidth=1.2, linestyle='--', alpha=0.9, zorder=0)
            plt.setp(ax_left.spines.values(), color='none')
            ax_left.set_ylabel('Observed daily earthquake count', labelpad=15)
            ax_left.set_xlabel('Date', labelpad=15)
            ax_left.tick_params(axis='x', rotation=45, labelsize=10)
            ax_left.grid(axis="y", linestyle='--', linewidth=1, zorder=0, color='palevioletred')

            seq_config = sequences[i]
            model_configs = [cfg for cfg in seq_config if len(cfg['df']) > 0]

            # Plot confidence intervals and step functions
            for cfg in model_configs:
                cfg_dates = pd.to_datetime(cfg['df'].date, utc=True)
                ax_right.fill_between(cfg_dates, cfg['plow'], cfg['phigh'],
                                linewidth=1.5, edgecolor='grey', facecolor='lightgrey', alpha=0.2, step='mid', zorder=0)
                ax_right.step(cfg_dates, cfg['df'][cfg['n_col']], '-.', color=cfg['color'],
                        where='mid', linewidth=2.5, zorder=1, label=cfg['label'])
                # Iterate over dates as well to match x and y dimensions
                for date, obs, forecast_low, forecast_up in zip(dates_arr[mask], obse_daily_count[mask], cfg['plow'], cfg['phigh']):
                    if obs >= forecast_low and obs <= forecast_up:
                        ax_right.plot(date, obs, 'o', markeredgecolor='k', color='white', markersize=18, alpha=0.4, zorder=2) # color='#4575b4',
                    else:
                        ax_right.plot(date, obs, 'o', markeredgecolor='k', color='#d73027', markersize=18, alpha=0.4, zorder=2)

            ax_right.legend(fontsize=12, facecolor='whitesmoke', edgecolor='grey', loc='upper right')
            ax_right.axvline(x=w_start + pd.Timedelta(days=4), ymin=0 , ymax=5, c='k', linewidth=1.2, linestyle='--', alpha=0.9, zorder=0)
            plt.setp(ax_right.spines.values(), color='none')
            ax_right.set_xlabel('Date', labelpad=15)
            ax_right.tick_params(axis='x', rotation=45, labelsize=10)
            ax_right.grid(axis="y", linestyle='--', linewidth=1, zorder=0, color='palevioletred')

            # Synchronize y-limits between the left and right axes
            ax_right.set_ylim(ax_left.get_ylim())

        if len(axes_list) > 0:
            axes_list[-1][0].set_xlabel('Date')
            axes_list[-1][1].set_xlabel('Date')

        plt.tight_layout()
        plt.show()

def plot_cumulative_number_of_events_plus_all_benchmarks(model_dates, model_counts, catalogue, models_name, forecast_dates, plot_configs, ax=None, window_start=None, window_end=None):
    if ax is None:
        fig, ax = plt.subplots(2, 1, figsize=(14, 12), gridspec_kw={'height_ratios': [1, 3], 'hspace': 0}, sharex=True)
    EVENTS = [
    ("2010-04-04", 7.2, "2010 $M_w$ 7.2 El Mayor-\nCucapah earthquake",  7.65,  120, "left"),
    ("2010-01-10", 6.5, "2010 $M_w$ 6.5\nFerndale earthquake",           7.10, -120, "right"),
    ("2012-08-26", 5.2, "2012 $M_w$ ≥ 3.95 Brawley\nseismic swarm",     5.85,    0, "center"),
    ("2014-08-24", 6.0, "2014 $M_w$ 6.0 South\nNapa earthquake",         6.55,  120, "left"),
    ("2014-03-10", 6.8, "2014 $M_w$ 6.8 Mendocino\narea earthquake",     7.2, -125, "center"),]

    # SINGLE REFERENCE X-AXIS
    ref_dates = pd.to_datetime(model_dates, utc=True).normalize().to_pydatetime()
    if len(ref_dates) == 0:
        return ax

    # Normalize catalog datetimes to align perfectly with the reference daily grid
    cat_dates = pd.to_datetime(catalogue.get_datetimes(), utc=True).normalize().to_pydatetime()
    cat_mags = np.array(catalogue.get_magnitudes())

    if window_start and window_end:
        window_start = pd.to_datetime(window_start, utc=True).to_pydatetime()
        window_end = pd.to_datetime(window_end, utc=True).to_pydatetime()
        cat_mask = (cat_dates >= window_start) & (cat_dates <= window_end)
        plot_cat_dates = cat_dates[cat_mask]
        plot_cat_mags = cat_mags[cat_mask]
        ax[1].set_xlim(window_start, window_end)
        mask_ref = (ref_dates >= window_start) & (ref_dates <= window_end)
        plot_ref_dates = ref_dates[mask_ref]
    else:
        plot_cat_dates = cat_dates
        plot_cat_mags = cat_mags
        ax[1].set_xlim(datetime(2007, 1, 1, 0, 0, tzinfo=timezone.utc), datetime(2018, 12, 30, 0, 0, tzinfo=timezone.utc))
        plot_ref_dates = ref_dates

    ax[0].set_ylim(4.0, 7.5)
    ax[0].grid(axis="y", linestyle='--', linewidth=1, zorder=0)
    plt.setp(ax[0].spines.values(), color='white')
    ax[0].yaxis.set_ticks(np.arange(4.0, 7.5, step=1.0))
    ax[0].yaxis.tick_right()
    ax[0].yaxis.set_label_position("right")

    if len(plot_cat_dates) > 0:
        ax[0].vlines(plot_cat_dates, [0], plot_cat_mags, linewidth=0.5, color='grey', alpha=0.3)
        z = (5.5**np.array(plot_cat_mags))*0.002
        ax[0].scatter(plot_cat_dates, plot_cat_mags, color='k', marker='o', edgecolor='grey', s=z, zorder=10)
        for d in plot_cat_dates:
          ax[1].axvline(d, color='grey', linewidth=0.5, zorder=0, alpha=0.3)

    ax[0].set_ylim(4.0, 7.6)
    ax[0].set_ylabel('Magnitude', fontsize=22, rotation=270, labelpad=30)

    ax[1].set_ylabel('Cumulative number of $\\mathregular{M_w}\\geq$ 3.95 earthquakes', fontsize=22)
    plt.setp(ax[1].spines.values(), color='None')
    ax[1].grid(axis="y", linestyle='--', linewidth=1, zorder=0)
    ax[1].tick_params(axis='x', rotation=45, labelsize=14)

    bbox_props = dict(boxstyle="round,pad=0.25", fc="white", ec="0.6", lw=0.7)
    for date_str, event_mag, label, text_mag, day_offset, ha in EVENTS:
        t_event = pd.to_datetime(date_str, utc=True).to_pydatetime()

        # In windowed plots, only show the event if it's in the window, and scale the text offset down.
        if window_start and window_end:
            if not (window_start <= t_event <= window_end):
                continue
            # Scale the offset down from ~120 days to ~2 days to fit the window view
            day_offset = np.sign(day_offset) * 2 if day_offset != 0 else 0

        t_text  = t_event + pd.Timedelta(days=day_offset)
        va = "bottom" if text_mag > event_mag else "top"
        ax[0].annotate(
            label,
            xy=(t_event, event_mag),
            xytext=(t_text, text_mag),
            fontsize=11 if not (window_start and window_end) else 14, ha=ha, va=va,
            bbox=bbox_props,
            arrowprops=dict(arrowstyle="-", color="0.3", lw=0.7),
            zorder=5,
        )
    max_y = 0

    # 1. Plot Benchmarks using reference dates
    for name in models_name:
        counts, offset, color = plot_configs[name]
        dates_raw = np.sort(forecast_dates[name]) if name == 'ETAS-DROneDayMd2.95' else np.array(forecast_dates[name])
        bm_dates = pd.to_datetime(dates_raw, utc=True).normalize().to_pydatetime()
        bm_cum = counts.cumsum() + offset

        # Interpolate/Step-evaluate benchmark cumulative counts at the reference dates
        y_vals = np.zeros(len(plot_ref_dates))
        for i, rd in enumerate(plot_ref_dates):
            if len(bm_dates) == 0 or rd < bm_dates[0] or rd > bm_dates[-1]:
                y_vals[i] = np.nan
            else:
                idx = np.searchsorted(bm_dates, rd, side='right') - 1
                y_vals[i] = bm_cum[idx]

        if window_start and window_end and len(y_vals) > 0:
            valid_mask = ~np.isnan(y_vals)
            if np.any(valid_mask):
                baseline = y_vals[valid_mask][0]
                y_vals = y_vals - baseline

        if len(plot_ref_dates) > 0:
            mask = ~np.isnan(y_vals)
            if np.any(mask):
                plot_dates = np.array(plot_ref_dates)[mask]
                plot_y = y_vals[mask]
                ax[1].step(plot_dates, plot_y, zorder=2, alpha=0.5, linewidth=1.5, color=color, where='post', label=name)
                valid_y = y_vals[mask]
                if len(valid_y) > 0:
                    max_y = max(max_y, np.max(valid_y))

    # 2. Plot Candidate Model using reference dates
    mcounts = np.array(model_counts)
    cum_model = np.cumsum(mcounts)
    if window_start and window_end:
        m_mask = (ref_dates >= window_start) & (ref_dates <= window_end)
        if np.any(m_mask):
            # Start from zero in the window
            w_cum_model = cum_model[m_mask]
            w_cum_model = w_cum_model - w_cum_model[0]
            ax[1].step(plot_ref_dates, w_cum_model, zorder=2, alpha=0.8, linewidth=2.5, color='red', where='post', label='Neural ETAS')
            max_y = max(max_y, w_cum_model[-1])
    else:
        if len(plot_ref_dates) > 0:
            ax[1].step(plot_ref_dates, cum_model, zorder=2, alpha=0.8, linewidth=2.5, color='red', where='post', label='Neural ETAS')
            max_y = max(max_y, cum_model[-1])

    # 3. Plot Observations using reference dates
    obs_cum = np.zeros(len(plot_ref_dates))
    for i, rd in enumerate(plot_ref_dates):
        # Count events strictly before the *end* of this reference day (which is rd + 1 day)
        obs_cum[i] = np.sum(cat_dates < (rd + pd.Timedelta(days=1)))

    if window_start and window_end and len(obs_cum) > 0:
        obs_cum = obs_cum - obs_cum[0]

    if len(plot_ref_dates) > 0:
        ax[1].step(plot_ref_dates, obs_cum, color='k', linestyle='--', zorder=2, linewidth=3.5, where='post', alpha=0.5, label='$\\mathregular{M_w}\\geq$ 3.95 Observations')
        max_y = max(max_y, np.max(obs_cum))

    if window_start and window_end:
        # Determine minimum Y to zoom in properly during windows
        valid_ys = y_vals[~np.isnan(y_vals)] if 'y_vals' in locals() else []
        min_bm_y = np.min(valid_ys) if len(valid_ys) > 0 else 0
        min_y = min(np.min(obs_cum), min_bm_y, np.min(w_cum_model)) if len(plot_ref_dates) > 0 else 0
        ax[1].set_ylim(max(0, min_y - 5), max_y + 5 if max_y > 0 else 10)
    else:
        ax[1].set_ylim(-5, max_y + 20)

    ax[1].legend(framealpha=1.0)

    plt.rc('xtick', labelsize=20)
    plt.rc('ytick', labelsize=20)
    return ax

def plot_consistency_test(eval_results, n_models, normalize=False, one_sided_lower=True, plot_args=None, variance=None, ax=None):
    try:
        results = list(eval_results)
    except TypeError:
        results = [eval_results]

    if plot_args is None:
        plot_args = {}
    figsize= plot_args.get('figsize', (7,7))
    xlabel = plot_args.get('xlabel', 'X')
    xlabel_fontsize = plot_args.get('xlabel_fontsize', None)
    xticks_fontsize = plot_args.get('xticks_fontsize', None)
    ylabel_fontsize = plot_args.get('ylabel_fontsize', None)
    color = plot_args.get('color', 'black')
    linewidth = plot_args.get('linewidth', None)
    capsize = plot_args.get('capsize', 4)
    hbars = plot_args.get('hbars', True)
    tight_layout = plot_args.get('tight_layout', True)
    percentile = plot_args.get('percentile', 95)

    if ax is None:
        fig, ax = plt.subplots(figsize=(6, n_models + 0.4))
    xlims = []

    for index, res in enumerate(results):
        if res.test_distribution[0] == 'poisson':
            plow = scipy.stats.poisson.ppf((1 - percentile/100.)/2., res.test_distribution[1])
            phigh = scipy.stats.poisson.ppf(1 - (1 - percentile/100.)/2., res.test_distribution[1])
            observed_statistic = res.observed_statistic

        elif res.test_distribution[0] == 'negative_binomial':
            var = variance[index]
            observed_statistic = res.observed_statistic
            mean = res.test_distribution[1]
            upsilon = 1.0 - ((var - mean) / var)
            tau = (mean**2 /(var - mean))
            phigh = scipy.stats.nbinom.ppf((1 - percentile/100.)/2., tau, upsilon)
            plow = scipy.stats.nbinom.ppf(1 - (1 - percentile/100.)/2., tau, upsilon)
        else:
            if normalize:
                test_distribution = numpy.array(res.test_distribution) - res.observed_statistic
                observed_statistic = 0
            else:
                test_distribution = numpy.array(res.test_distribution)
                observed_statistic = res.observed_statistic

        if not numpy.isinf(observed_statistic):
            low = observed_statistic - plow
            high = phigh - observed_statistic
            xlims.append((plow, phigh, observed_statistic))
            if one_sided_lower:
                if observed_statistic >= plow and phigh < observed_statistic:
                    xt = numpy.linspace(phigh, 99999, 100)
                    yt = numpy.ones(100) * index
                    ax.plot(xt, yt, linestyle='--', linewidth=linewidth, color=color)

        else:
            print('Observed statistic diverges for forecast %s, index %i.'
                  ' Check for zero-valued bins within the forecast'% (res.sim_name, index))
            ax.barh(index, 99999, left=-10000, height=1, color=['red'], alpha=0.5)

    ax.set_yticks(numpy.arange(len(results)))
    ax.set_yticklabels([res.sim_name for res in results], fontsize=22)
    ax.set_ylim([-0.5, len(results)-0.5])
    if hbars:
        yTickPos = ax.get_yticks()
        if len(yTickPos) >= 2:
            ax.barh(yTickPos, numpy.array([99999] * len(yTickPos)), left=-10000,
                    height=(yTickPos[1] - yTickPos[0]), color=['ghostwhite', 'lightsteelblue'], alpha=0.3, zorder=0)
    ax.set_xlabel(xlabel, fontsize=16)
    ax.tick_params(axis='x', labelsize=16)
    ax.invert_yaxis() # Fix the reversed order of models
    return ax

def plot_percentages_and_intervals(test_results, ax, var=None, show_bar=False):
    variance = var
    percentile = 95.0

    cmap = plt.get_cmap('jet')
    norm = matplotlib.colors.Normalize(vmin=0, vmax=100)

    for index, res in enumerate(test_results):
        if res.test_distribution[0] == 'negative_binomial':
            mean = res.test_distribution[1]
            upsilon = 1.0 - ((variance[index] - mean) / variance[index])
            tau = (mean**2 /(variance[index] - mean))
            plow95 = scipy.stats.nbinom.ppf(1 - (1 - percentile/100.)/2., tau, upsilon)
            phigh95 = scipy.stats.nbinom.ppf((1 - percentile/100.)/2., tau, upsilon)
            low95 = res.observed_statistic - plow95
            high95 = phigh95 - res.observed_statistic
            observed_statistic =  res.observed_statistic

            if not numpy.isinf(res.observed_statistic):
                ax.hlines(y=index, xmin=plow95, xmax=phigh95, linestyle='--', colors='k', lw=1.5, alpha=0.4)

        elif res.test_distribution[0] == 'poisson':
            mean = res.test_distribution[1]
            plow95 = scipy.stats.poisson.ppf((1 - percentile/100.)/2., res.test_distribution[1])
            phigh95 = scipy.stats.poisson.ppf(1 - (1 - percentile/100.)/2., res.test_distribution[1])
            low95 = res.observed_statistic - plow95
            high95 = phigh95 - res.observed_statistic
            observed_statistic =  res.observed_statistic

            delta = np.abs(100.0 - ((res.test_distribution[1] * 100.0) / res.observed_statistic))
            forecast_delta_color = cmap(norm(min(delta, 100)))

            if not numpy.isinf(res.observed_statistic):
                percentile_lims = numpy.array([[mean - plow95, phigh95 - mean]]).T
                ax.errorbar(mean, index, xerr=percentile_lims, color='k', lw=3.0, alpha=0.95)
                ax.scatter(mean, index, edgecolor='k', facecolor=forecast_delta_color, marker="o", s=200, linewidth=0.8, zorder=2)

            ax.scatter(observed_statistic, index, edgecolor='k', facecolor='none', marker="o", s=300, linewidth=2.5, zorder=3)


    if show_bar:
        sm = plt.cm.ScalarMappable(cmap=cmap, norm=norm)
        sm.set_array([])
        cbar = ax.get_figure().colorbar(sm, ax=ax, location='top', fraction=0.046, pad=0.04)
        cbar.set_label(r'$\Delta$ (%)', fontsize=18)
        cbar.ax.tick_params(labelsize=14)

    return ax

def compute_windowed_n_tests(window_start, window_end, min_mw=3.95):
    w_start = pd.to_datetime(window_start, utc=True)
    w_end = pd.to_datetime(window_end, utc=True)

    start_epoch = csep.utils.time_utils.strptime_to_utc_epoch(f"{w_start.strftime('%Y-%m-%d')} 00:00:00.0")
    end_epoch = csep.utils.time_utils.strptime_to_utc_epoch(f"{(w_end + pd.Timedelta(days=1)).strftime('%Y-%m-%d')} 00:00:00.0")

    models_to_eval = [
        ('ETAS', ETAS, 'n_ETAS', 'data/catalogues/catalogue_2007_2018.obj'),
        ('ETAS-DROneDayMd2', ETAS_DROneDayMd2, 'n_ETAS_DROneDayMd2', 'data/catalogues/catalogue_2007_2018.obj'),
        ('ETAS-HWMd3', ETAS_HWMd3, 'n_ETAS_HWMd3', 'data/catalogues/catalogue_2007_2018.obj'),
        ('ETAS-DROneDayMd2.95', ETAS_DROneDayMd295, 'n_ETAS_DROneDayMd295', 'data/catalogues/catalogue_2007_2018.obj'),
        ('STEP', STEP, 'n_STEP', 'data/catalogues/catalogue_2007_2018.obj'),
        # ('STEPJAVA', STEPJAVA, 'n_STEPJAVA', 'data/catalogues/catalogue_2007_2018_sj.obj'),
        ('ETAS-DROneDayPPEMd2', ETAS_DROneDayPPEMd2, 'n_ETAS_DROneDayPPEMd2', 'data/catalogues/catalogue_2007_2018.obj'),
        ('K3Md2', K3Md2, 'n_K3Md2', 'data/catalogues/catalogue_2007_2018.obj'),
        ('ETAS-HW-K3-AVERAGE-Md2', ETAS_HW_K3_AVERAGE_Md2, 'n_ETAS_HW_K3_AVERAGE_Md2', 'data/catalogues/catalogue_2007_2018.obj')
    ]

    window_tests = []
    for name, df, col, cat_path in models_to_eval:
        if df is None or len(df) == 0: continue

        df_dates = pd.to_datetime(df['date'], utc=True)
        mask = (df_dates >= w_start) & (df_dates <= w_end)
        if not mask.any():
            continue

        fore_cnt = df.loc[mask, col].sum()

        with open(cat_path, 'rb') as obj:
            cat = pickle.load(obj)

        cat = cat.filter([f'origin_time >= {start_epoch}', f'origin_time < {end_epoch}'])
        if min_mw:
            cat = cat.filter([f'magnitude >= {min_mw}'])

        res = EvaluationResult()
        res.test_distribution = ('poisson', fore_cnt)
        res.name = 'Poisson N-Test'
        res.observed_statistic = cat.event_count

        delta1 = 1.0 - scipy.stats.poisson.cdf(res.observed_statistic - 1e-6, fore_cnt)
        delta2 = scipy.stats.poisson.cdf(res.observed_statistic + 1e-6, fore_cnt)
        res.quantile = (delta1, delta2)
        res.status = 'normal'
        res.min_mw = min_mw
        res.sim_name = f'{name} (n={cat.event_count})'
        window_tests.append(res)

    return window_tests

def plot_comparative_n_test_results(forecasts_aligned, full_region_cat, mags, agg_forecasts, window_start=None, window_end=None, ax=None):
    start_epoch = pd.Timestamp(forecasts_aligned.index[0]).value // 10**6
    end_epoch = (pd.Timestamp(forecasts_aligned.index[-1]) + pd.Timedelta(days=1)).value // 10**6
    test_catalog = full_region_cat.filter([f'origin_time >= {start_epoch}', f'origin_time < {end_epoch}'], in_place=False)
    test_catalog = test_catalog.filter([f'magnitude >= {mags[0]}'], in_place=False)

    ntest_candidate = number_test(agg_forecasts.data.flatten(), test_catalog)
    ntest_candidate.sim_name = f'Neural ETAS (n={test_catalog.event_count})'

    if window_start and window_end:
        n4_tests = [ntest_candidate] + compute_windowed_n_tests(window_start, window_end, min_mw=mags[0])
    else:
        ntest_ETAS.sim_name = f'ETAS (n={catalogue_ETAS.event_count})'
        ntest_ETAS_DROneDayMd2.sim_name = f'ETAS-DROneDayMd2 (n={catalogue_ETAS_DROneDayMd2.event_count})'
        ntest_ETAS_HWMd3.sim_name = f'ETAS-HWMd3 (n={catalogue_ETAS_HWMd3.event_count})'
        ntest_ETAS_DROneDayMd295.sim_name = f'ETAS-DROneDayMd2.95 (n={catalogue_ETAS_DROneDayMd295.event_count})'
        ntest_STEP.sim_name = f'STEP (n={catalogue_STEP.event_count})'
        ntest_STEPJAVA.sim_name = f'STEPJAVA (n={catalogue_STEPJAVA.event_count})'
        ntest_ETAS_DROneDayPPEMd2.sim_name = f'ETAS-DROneDayPPEMd2 (n={catalogue_ETAS_DROneDayPPEMd2.event_count})'
        ntest_K3Md2.sim_name = f'K3Md2 (n={catalogue_K3Md2.event_count})'
        ntest_ETAS_HW_K3_AVERAGE_Md2.sim_name = f'ETAS-HW-K3-AVERAGE-Md2 (n={catalogue_ETAS_HW_K3_AVERAGE_Md2.event_count})'

        n4_tests = [
        ntest_candidate,
        ntest_ETAS,
        ntest_ETAS_DROneDayMd2,
        ntest_ETAS_HWMd3,
        ntest_ETAS_DROneDayMd295,
        ntest_STEP,
        ntest_STEPJAVA,
        ntest_ETAS_DROneDayPPEMd2,
        ntest_K3Md2,
        ntest_ETAS_HW_K3_AVERAGE_Md2
        ]

    ax = plot_consistency_test(n4_tests, n_models=(len(n4_tests) - 1)/2, one_sided_lower=False, plot_args={'xlabel': 'Number of earthquakes'}, ax=ax)
    plt.setp(ax.spines.values(), color='grey')
    ax = plot_percentages_and_intervals(n4_tests, ax, show_bar=True)

    ax.yaxis.tick_right()
    if window_start and window_end:
        # Ensure zoom properly fits
        max_obs = max((res.observed_statistic for res in n4_tests), default=0)
        ax.set_xlim(-2, max_obs * 1.5 + 5)
    else:
        ax.set_xlim(-50,750)
    ax.set_title('')
    return ax

def plot_combined_cumulative_and_n_test(model_dates, model_counts, catalogue, models_name, forecast_dates, plot_configs, forecasts_aligned, full_region_cat, mags, agg_forecasts, window_start=None, window_end=None):
    fig = plt.figure(figsize=(24, 12))
    gs = fig.add_gridspec(2, 2, width_ratios=[2, 1], height_ratios=[1, 3], hspace=0, wspace=0.25)

    ax0 = fig.add_subplot(gs[0, 0])
    ax1 = fig.add_subplot(gs[1, 0], sharex=ax0)
    ax0.tick_params(bottom=False, labelbottom=False)
    ax_cum = [ax0, ax1]

    ax2 = fig.add_subplot(gs[:, 1])

    plot_models_name = models_name
    if window_start and window_end:
        plot_models_name = [name for name in models_name if name != 'STEPJAVA']

    plot_cumulative_number_of_events_plus_all_benchmarks(model_dates, model_counts, catalogue, plot_models_name, forecast_dates, plot_configs, ax=ax_cum, window_start=window_start, window_end=window_end)

    if window_start and window_end:
        mask = (pd.to_datetime(forecasts_aligned.index, utc=True) >= pd.to_datetime(window_start, utc=True)) & (pd.to_datetime(forecasts_aligned.index, utc=True) <= pd.to_datetime(window_end, utc=True))
        f_aligned_window = forecasts_aligned[mask].copy(deep=True)
        if not f_aligned_window.empty:
            data_array = np.zeros_like(f_aligned_window.iloc[0].data)
            for day in f_aligned_window.index:
                data_array += f_aligned_window[day].data
            agg_f_window = GriddedForecast(data=data_array, region=agg_forecasts.region, magnitudes=agg_forecasts.magnitudes, start_time=f_aligned_window.index[0], end_time=f_aligned_window.index[-1] + pd.Timedelta(days=1))
            plot_comparative_n_test_results(f_aligned_window, full_region_cat, mags, agg_f_window, window_start=window_start, window_end=window_end, ax=ax2)
    else:
        plot_comparative_n_test_results(forecasts_aligned, full_region_cat, mags, agg_forecasts, ax=ax2)

    plt.savefig('results/Figure3_combined.png', dpi=300, bbox_inches='tight')
    plt.show()

def plot_spatial_quantiles(active_days_arrays, model_names, filename='results/Figure5_with_Candidate.png'):
    fig = plt.figure(figsize=(18, 14))

    n_cols = 4
    n_rows = int(np.ceil(len(model_names) / n_cols))

    for i in range(len(active_days_arrays)):
        squantiles = np.sort(active_days_arrays[i])
        # Drop any NaNs just in case
        squantiles = squantiles[~np.isnan(squantiles)]
        uniform_pdf = np.linspace(0.0, 1.0, len(squantiles))

        ax = fig.add_subplot(n_rows, n_cols, i + 1)
        plt.grid(which='both', linestyle='--', color='grey', zorder=0, linewidth=0.75)
        plt.plot((0, 1), (0, 1), '--', color='grey', linewidth = 1.5, zorder=2)
        plt.yticks(np.arange(0, 1.001, step=0.2), fontsize=16)
        plt.xticks(np.arange(0, 1.001, step=0.2), fontsize=16)
        plt.ylim(-0.05,1.05)
        plt.xlim(-0.05,1.05)

        # Highlight candidate model in red
        color = '#D32D41' if model_names[i] == 'Neural ETAS' else 'blue'
        lw = 1.5 if model_names[i] == 'Neural ETAS' else 0.5

        plt.plot(squantiles, uniform_pdf, linewidth=lw, color=color, zorder=2)
        plt.fill_between(squantiles, uniform_pdf, squantiles, where=(uniform_pdf > squantiles), alpha=0.5, interpolate=True, color=color, zorder=1)
        plt.fill_between(squantiles, uniform_pdf, squantiles, where=(uniform_pdf <= squantiles), alpha=0.5, interpolate=True, color=color, zorder=1)

        # Dynamically determine if axis ticks should be labeled
        col = i % n_cols
        lb = (i + n_cols >= len(model_names))
        lf = (col == 0)
        plt.tick_params(labelleft=lf, labelbottom=lb)
        plt.title(model_names[i], fontsize=16)

        # Calculate Area (A) and KS p-value
        if len(squantiles) > 0:
            area = np.trapz(np.abs(squantiles - uniform_pdf), uniform_pdf)
            _, p_val = scipy.stats.ks_2samp(squantiles, uniform_pdf)
        else:
            area, p_val = np.nan, np.nan

        ax.text(0.05, 0.90, f'A = {area:.3f}\n$K_s$ = {p_val:.3f}',
                transform=ax.transAxes, ha='left', va='top', fontsize=14,
                bbox=dict(facecolor='white', alpha=0.8, edgecolor='none', pad=2), zorder=3)

    fig.text(0.515, -0.012, 'Observed spatial quantiles', fontsize=25, ha='center', va='center')
    fig.text(-0.02, 0.508, 'Uniform spatial quantiles', fontsize=25, ha='center', va='center', rotation='vertical')
    fig.tight_layout()
    plt.savefig(filename, dpi=150, bbox_inches='tight')
    plt.show()

def plot_magnitude_test(agg_forecasts, forecasts_aligned, filename='results/Figure7.png', full_region_cat=None):
    # --- Compute Neural ETAS Magnitude Test metrics ---
    start_epoch = pd.Timestamp(forecasts_aligned.index[0]).value // 10**6
    end_epoch = (pd.Timestamp(forecasts_aligned.index[-1]) + pd.Timedelta(days=1)).value // 10**6
    netas_obs_cat = full_region_cat.filter([f'origin_time >= {start_epoch}', f'origin_time < {end_epoch}'], in_place=False)
    netas_obs_cat = netas_obs_cat.filter([f'magnitude >= 3.95'], in_place=False)

    netas_cummag = np.sum(agg_forecasts.data, axis=0)
    netas_ncount_sum = np.sum(netas_cummag)
    netas_cummag_nor = netas_cummag * (netas_obs_cat.event_count / netas_ncount_sum)

    percentile = 95.0
    Neural_ETAS_cummag_low = scipy.stats.poisson.ppf((1 - percentile/100.)/2., netas_cummag_nor)
    Neural_ETAS_cummag_high = scipy.stats.poisson.ppf(1 - (1 - percentile/100.)/2., netas_cummag_nor)

    Neural_ETAS_mtest = magnitude_test(netas_cummag, netas_obs_cat.magnitude_counts())
    kstest_Neural_ETASm = calculate_pvalues(netas_obs_cat, netas_cummag_nor)

    globals()['Neural_ETAS_cummag_low'] = Neural_ETAS_cummag_low
    globals()['Neural_ETAS_cummag_high'] = Neural_ETAS_cummag_high
    globals()['Neural_ETAS_mtest'] = Neural_ETAS_mtest
    globals()['kstest_Neural_ETASm'] = kstest_Neural_ETASm
    # --------------------------------------------------

    mw_min = 3.95
    mw_max = 8.95
    dmw = 0.1
    mws = np.arange(mw_min, mw_max, dmw)
    seed = 123456

    fig = plt.figure(figsize=(14, 14))

    # Grid layout definition for Figure 7 including Neural ETAS
    fig7_layout = [
        'ETAS', 'ETAS_DROneDayMd2', 'ETAS_HWMd3', 'ETAS_DROneDayMd295',
        'STEP', 'STEPJAVA',
        'ETAS_DROneDayPPEMd2',
        'K3Md2',
        'ETAS_HW_K3_AVERAGE_Md2',
        'Neural_ETAS'  # Added Neural ETAS
    ]

    titles = {
        'ETAS': 'ETAS',
        'ETAS_DROneDayMd2': 'ETAS-DROneDayMd2',
        'ETAS_HWMd3': 'ETAS-HWMd3',
        'ETAS_DROneDayMd295': 'ETAS-DROneDayMd2.95',
        'STEP': 'STEP',
        'STEPJAVA': 'STEPJAVA',
        'ETAS_DROneDayPPEMd2': 'ETAS-DROneDayPPEMd2',
        'K3Md2': 'K3Md2',
        'ETAS_HW_K3_AVERAGE_Md2': 'ETAS-HW-K3-AVERAGE-Md2',
        'Neural_ETAS': 'Neural ETAS'
    }

    # Provide catalog mappings for observations plotting
    cat_map = {
        'ETAS': catalogue, 'ETAS_DROneDayMd2': catalogue_ETAS_DROneDayMd2, 'ETAS_HWMd3': catalogue_ETAS_HWMd3, 'ETAS_DROneDayMd295': catalogue_ETAS_DROneDayMd295,
        'STEP': catalogue_STEP, 'STEPJAVA': catalogue_STEPJAVA,
        'ETAS_DROneDayPPEMd2': catalogue_ETAS_DROneDayPPEMd2,
        'K3Md2': catalogue_K3Md2,
        'ETAS_HW_K3_AVERAGE_Md2': catalogue_ETAS_HW_K3_AVERAGE_Md2,
        'Neural_ETAS': netas_obs_cat
    }

    for i, model in enumerate(fig7_layout):
        ax = fig.add_subplot(4, 3, i + 1) # Updated to 4x3 to fit 10 models

        # Slice low and high to match mws length
        low = globals()[f'{model}_cummag_low'][:len(mws)]
        high = globals()[f'{model}_cummag_high'][:len(mws)]
        obs_mags = list(cat_map[model].magnitude_counts())
        # Pad obs_mags if lengths don't match mws (due to empty high magnitude bins)
        if len(obs_mags) < len(mws):
             obs_mags.extend([0] * (len(mws) - len(obs_mags)))
        elif len(obs_mags) > len(mws):
             obs_mags = obs_mags[:len(mws)]

        ax.set_xticks(np.arange(4.0, 8.0, step=1.0))
        ax.set_xticks(np.arange(4.5, 8.0, step=0.5), minor=True)
        ax.xaxis.set_major_formatter(FormatStrFormatter('%.1f'))
        ax.set_xlim(3.75, 7.25)
        ax.set_yticks([10**0, 10**1, 10**2])
        ax.set_ylim(0.05, 2.001*10**2)

        ax.set_yscale("log")
        ax.grid(which='both', linestyle='--', color='grey', linewidth=0.75, zorder=0, axis='x')
        ax.grid(which='major', linestyle='--', color='grey', linewidth=0.75, zorder=0, axis='y')

        color = 'red' if model == 'Neural_ETAS' else 'blue'

        ax.fill_between(mws, low, high, linewidth=1, edgecolor='grey', facecolor='grey', alpha=0.2, step='mid', zorder=2)
        ax.step(mws, obs_mags, linewidth=2, color=color, where='mid', zorder=2)

        ax.set_title(titles[model], fontsize=16)

        m_test_obj = globals().get(f'{model}_mtest')
        m_val = m_test_obj.quantile if m_test_obj else np.nan

        ks_name = f'kstest_{model}m'
        ks_val = globals().get(ks_name, np.nan)

        ax.text(0.95, 0.90, f'φ = {m_val:.3f}\n$K_s$ = {ks_val:.3f}',
                transform=ax.transAxes, ha='right', va='top', fontsize=14,
                bbox=dict(facecolor='white', alpha=0.7, edgecolor='none', pad=2), zorder=3)

        ax.tick_params(labelsize=20)
        if i % 3 != 0:
            ax.set_yticklabels([])
        if i < 7: # Updated bottom-row logic for 4x3 grid
            ax.set_xticklabels([])

    fig.text(0.515, -0.012, 'Magnitude M$_\\mathrm{w}$', fontsize=25, ha='center', va='center')
    fig.text(-0.02, 0.515, 'Log$_{10}$ (Normalized number of earthquakes)', fontsize=25, ha='center', va='center', rotation='vertical')
    fig.tight_layout()
    plt.savefig(filename, dpi=150, bbox_inches='tight')
    plt.show()

def plot_information_gain(forecasts_aligned, test_y_aligned=None):
    forecasts_aligned_cp = copy.deepcopy(forecasts_aligned)
    test_y_aligned_cp = copy.deepcopy(test_y_aligned)

    with open ('data/catalogues/catalogue_2007_2018.obj', 'rb') as obj:
      catalogue = pickle.load(obj)

    cat_aux1 = copy.deepcopy(catalogue)
    cat_aux1.filter(f'origin_time >= {time_utils.strptime_to_utc_epoch('2007-08-01 00:00:00.0')}')
    cat_aux1.filter(f'origin_time < {time_utils.strptime_to_utc_epoch('2009-01-01 00:00:00.0')}')

    cat_aux2 = copy.deepcopy(catalogue)
    cat_aux2.filter(f'origin_time >= {time_utils.strptime_to_utc_epoch('2009-01-01 00:00:00.0')}')
    cat_aux2.filter(f'origin_time < {time_utils.strptime_to_utc_epoch('2010-09-01 00:00:00.0')}')

    cat_aux3 = copy.deepcopy(catalogue)
    cat_aux3.filter(f'origin_time >= {time_utils.strptime_to_utc_epoch('2010-09-01 00:00:00.0')}')
    cat_aux3.filter(f'origin_time < {time_utils.strptime_to_utc_epoch('2012-07-01 00:00:00.0')}')

    cat_aux4 = copy.deepcopy(catalogue)
    cat_aux4.filter(f'origin_time >= {time_utils.strptime_to_utc_epoch('2012-07-01 00:00:00.0')}')
    cat_aux4.filter(f'origin_time < {time_utils.strptime_to_utc_epoch('2012-10-01 00:00:00.0')}')

    cat_aux5 = copy.deepcopy(catalogue)
    cat_aux5.filter(f'origin_time >= {time_utils.strptime_to_utc_epoch('2013-01-21 00:00:00.0')}')
    cat_aux5.filter(f'origin_time < {time_utils.strptime_to_utc_epoch('2016-07-01 00:00:00.0')}')

    cat_aux6 = copy.deepcopy(catalogue)
    cat_aux6.filter(f'origin_time >= {time_utils.strptime_to_utc_epoch('2016-10-01 00:00:00.0')}')
    cat_aux6.filter(f'origin_time < {time_utils.strptime_to_utc_epoch('2018-06-30 00:00:00.0')}')

    # Deep copy catalogs
    cats = [cat_aux1, cat_aux2, cat_aux3, cat_aux4, cat_aux5, cat_aux6]

    # Deep copy Jolis DataFrames
    jolis = [joli_1.copy(deep=True), joli_2.copy(deep=True), joli_3.copy(deep=True),
             joli_4.copy(deep=True), joli_5.copy(deep=True), joli_6.copy(deep=True)]

    # Deep copy the lists of dates
    joli_dates_list = copy.deepcopy([joli_1dates, joli_2dates, joli_3dates,
                                     joli_4dates, joli_5dates, joli_6dates])

    # ---------------------------------------------------------
    # 2. PLOTTING AND DATA PROCESSING
    # ---------------------------------------------------------
    fig, axes = plt.subplots(nrows=2, ncols=3, figsize=(30, 16))
    axes = axes.flatten()

    panel_models = [
        [('STEP', 'joli_STEP', '#15B01A')],
        [('STEP', 'joli_STEP', '#15B01A')],
        [('STEP', 'joli_STEP', '#15B01A'), ('STEPJAVA', 'joli_STEPJAVA', '#C79FEF')],
        [('STEP', 'joli_STEP', '#15B01A')],
        [('ETAS-DROneDayMd2', 'joli_ETAS_DROneDayMd2', '#6a3d9a'),
         ('ETAS-HWMd3', 'joli_ETAS_HWMd3', 'teal'),
         ('ETAS-HW-K3-AVERAGE-Md2', 'joli_ETAS_HW_K3_Md2', '#708090'),
         ('ETAS-DROneDayPPEMd2', 'joli_ETAS_DROneDayPPEMd2', '#00FFFF'),
         ('K3Md2', 'joli_K3Md2', 'dodgerblue')],
        [('ETAS-DROneDayMd2', 'joli_ETAS_DROneDayMd2', '#6a3d9a'),
         ('ETAS-HWMd3', 'joli_ETAS_HWMd3', 'teal'),
         ('ETAS-DROneDayMd2.95', 'joli_ETAS_DROneDayMd295', '#fb9a99'),
         ('ETASSYN-DROneDayMd2.95', 'joli_ETASSYN_DROneDayMd295', 'brown'),
         ('ETAS-DROneDayPPEMd2', 'joli_ETAS_DROneDayPPEMd2', '#00FFFF')]
    ]

    # Compute LL for Neural ETAS
    netas_dates = []
    netas_ll = []
    for day in forecasts_aligned_cp.index:
        lam_model = np.array(forecasts_aligned_cp.loc[day].data, dtype=float, copy=True)
        n_obs = np.array(test_y_aligned_cp.loc[day].spatial_magnitude_counts(), dtype=float, copy=True)

        if lam_model.shape[1] == n_obs.shape[1] + 1:
            lam_model = lam_model[:, :-1]
        elif lam_model.shape[1] + 1 == n_obs.shape[1]:
            n_obs = n_obs[:, :-1]

        if lam_model.shape != n_obs.shape:
            min_mags = min(lam_model.shape[1], n_obs.shape[1])
            lam_model = lam_model[:, :min_mags]
            n_obs = n_obs[:, :min_mags]

        ll_model = compute_ll_model(lam_model, n_obs, 1e-10)
        netas_dates.append(day.strftime('%Y-%m-%d'))
        netas_ll.append(ll_model)

    netas_df = pd.DataFrame({'date': netas_dates, 'joli_NETAS': netas_ll})

    for i in range(len(jolis)):
        jolis[i] = pd.merge(jolis[i], netas_df, on='date', how='left')
        panel_models[i].append(('Neural ETAS', 'joli_NETAS', 'red'))

    xticklabels = [
        ['2007-09-01', '2007-11-01', '2008-01-01', '2008-03-01', '2008-05-01', '2008-07-01', '2008-09-01', '2008-11-01', '2009-01-01'],
        ['2009-01-01', '2009-03-01', '2009-05-01', '2009-07-01', '2009-09-01', '2009-11-01', '2010-01-01', '2010-03-01', '2010-05-01', '2010-07-01', '2010-09-01'],
        ['2010-10-01', '2011-01-01', '2011-04-01', '2011-07-01', '2011-10-01', '2012-01-01', '2012-04-01', '2012-07-01'],
        ['-5.0', '0.0', '5.0', '10.0', '15.0'],
        ['2013-01-01', '2013-07-01', '2014-01-01', '2014-07-01', '2015-01-01', '2015-07-01', '2016-01-01', '2016-07-01'],
        ['2016-10-01', '2017-01-01', '2017-04-01', '2017-07-01', '2017-10-01', '2018-01-01', '2018-04-01', '2018-07-01']
    ]

    EVENTS = [
        ("2010-04-04", 7.2, "2010 $M_w$ 7.2 El Mayor-\nCucapah earthquake", 7.65, 130, "left"),
        ("2010-01-10", 6.5, "2010 $M_w$ 6.5\nFerndale earthquake", 7.10, -120, "right"),
        ("2012-08-26", 5.2, "2012 $M_w$ ≥ 3.95 Brawley\nseismic swarm", 5.85, 0, "center"),
        ("2014-08-24", 6.0, "2014 $M_w$ 6.0 South\nNapa earthquake", 6.55, 120, "left"),
        ("2014-03-10", 6.8, "2014 $M_w$ 6.8 Mendocino\narea earthquake", 7.5, 125, "right"),
    ]

    for i, ax in enumerate(axes):
        ax.set_ylim(-5.0, 24.0)
        ax.grid(axis="y", linestyle='--', linewidth=1, zorder=0, color='palevioletred')

        cat = cats[i]
        cat_dates = pd.to_datetime(cat.get_datetimes(), utc=True).normalize().to_pydatetime()
        cat_mags = np.array(cat.get_magnitudes())

        if len(cat.get_datetimes()) > 0:
            ax.vlines(cat.get_datetimes(), ymin=-5.0, ymax=15, color='k' if i>0 else 'grey',
                      linewidth=0.5 if i!=3 else 0.7, zorder=0 if i>0 else 2, alpha=0.2 if i>0 else 0.7)
        if len(cat_dates) > 0:
            z = (5.5**np.array(cat_mags))*0.002
            y_mags = 15 + (cat_mags - 4.0) * 1.5
            ax.scatter(cat_dates, y_mags, color='k', marker='o', edgecolor='grey', s=z, zorder=10)

        bbox_props = dict(boxstyle="round,pad=0.25", fc="white", ec="0.6", lw=0.7)

        for date_str, event_mag, label, text_mag, day_offset, ha in EVENTS:
            t_event = pd.to_datetime(date_str, utc=True).to_pydatetime()
            if len(joli_dates_list[i]) > 0:
                window_start = min(joli_dates_list[i]).replace(tzinfo=timezone.utc)
                window_end = max(joli_dates_list[i]).replace(tzinfo=timezone.utc)

                if (window_start <= t_event <= window_end):
                    y_event = 15 + (event_mag - 4.0) * 1.5
                    y_text = 15 + (text_mag - 4.0) * 1.5
                    t_text = t_event + pd.Timedelta(days=np.sign(day_offset) * 2 if day_offset != 0 else 0)
                    va = "bottom" if text_mag > event_mag else "top"
                    ax.annotate(
                        label, xy=(t_event, y_event), xytext=(t_text, y_text),
                        fontsize=14, ha=ha, va=va, bbox=bbox_props,
                        arrowprops=dict(arrowstyle="-", color="0.3", lw=0.7), zorder=5,
                    )

        for model_name, col, color in panel_models[i]:
            df = jolis[i]
            valid_mask = ~df[col].isna()
            dates = np.array(joli_dates_list[i])[valid_mask]
            norm_cat = cats[i]
            # Directly use 'joli_ETAS' as baseline from the current dataframe
            y_vals = np.cumsum(df.loc[valid_mask, col].values - df.loc[valid_mask, 'joli_ETAS'].values) / len(np.unique(norm_cat.get_spatial_idx()))

            ax.step(dates, y_vals, zorder=2 if model_name != 'ETAS-DROneDayMd2' else 1,
                    alpha=0.8, linewidth=3, color=color, where='mid' if i!=3 else 'post', label=model_name)

        ax.step(joli_dates_list[i], np.zeros(len(joli_dates_list[i])), zorder=2, alpha=1,
                linewidth=3, color='#1f77b4', where='mid' if i!=3 else 'post', label='ETAS')

        plt.setp(ax.spines.values(), color="None")
        ax.yaxis.set_ticks(np.arange(-5.0, 15.01, step=5.0))

        if i != 3:
            ax.set_xticklabels(xticklabels[i])
        else:
            ax.set_yticklabels(xticklabels[i])

        for tick in ax.xaxis.get_major_ticks():
            tick.label1.set_fontsize(16)
            tick.label1.set_rotation(45)
        for tick in ax.yaxis.get_major_ticks():
            tick.label1.set_fontsize(16)

    fig.supylabel('Cumulative information gain per activated cell', fontsize=23, x=0.08)
    handles, labels = [], []
    for ax in axes:
        for handle, label in zip(*ax.get_legend_handles_labels()):
            if label not in labels:
                handles.append(handle)
                labels.append(label)

    fig.legend(handles, labels, loc='center', bbox_to_anchor=(0.5, 0.45), ncol=6, fontsize=18, framealpha=1, edgecolor='black')
    plt.subplots_adjust(wspace=0.2, hspace=0.55)
    plt.savefig('results/Figure8.png', dpi=300, bbox_inches='tight')
    plt.show()

# ===== deferred script code + baselines (exec'd verbatim) =====
def load_baselines():
    """Run the baseline-loading cell (kept byte-identical in
    _baselines.py) inside THIS module's namespace, so evaluate_fn
    and the plotting code resolve the baseline artifacts exactly as
    they do in the full notebook. cwd must be the reproducibility
    repo. Returns the ETAS baseline daily-score series."""
    from pathlib import Path as _P
    _src = (_P(__file__).parent / '_baselines.py').read_text()
    exec(compile(_src, str(_P(__file__).parent / '_baselines.py'),
                 'exec'), globals())
    return globals()['etas_scores_wrt_obs']
